import 'models.dart';

const currentCurriculumYear = '2026-2027';
const officialSourceLabel = 'المركز الوطني لتطوير المناهج والتقويم';

const curriculumSources = <CurriculumSource>[
  CurriculumSource(
    id: 'nccd-g12-en-s1-2026',
    subject: 'اللغة الإنجليزية',
    title: 'Jordan High Note Grade 12 - Student’s Book - Semester 1',
    semester: 'الفصل الدراسي الأول',
    academicYear: currentCurriculumYear,
    publisher: officialSourceLabel,
    status: 'متحقق ومفهرس',
    note: 'اعتماد نسخة Reprint 2026 ومطابقة بنية الوحدات والمهارات.',
  ),
  CurriculumSource(
    id: 'nccd-g12-chem-s1-2026',
    subject: 'الكيمياء',
    title: 'الكيمياء - كتاب الطالب - الصف الثاني عشر - المسار الأكاديمي',
    semester: 'الفصل الدراسي الأول',
    academicYear: currentCurriculumYear,
    publisher: officialSourceLabel,
    status: 'متحقق ومفهرس',
    note: 'الطبعة الثانية المنقحة؛ فُهرست الوحدات والدروس الرئيسة.',
  ),
  CurriculumSource(
    id: 'nccd-g12-math-s1-2026',
    subject: 'الرياضيات',
    title: 'الرياضيات - كتاب الطالب - الصف الثاني عشر - المسار الأكاديمي',
    semester: 'الفصل الدراسي الأول',
    academicYear: currentCurriculumYear,
    publisher: officialSourceLabel,
    status: 'مفهرس بمطابقة حديثة',
    note: 'وجود الكتاب مؤكد في صفحة المركز 2026-2027، وفُهرست وحداته وفق فهرس الخطة الجديدة مع إبقاء مستوى التحقق ظاهرًا للمستخدم.',
  ),
  CurriculumSource(
    id: 'nccd-g12-physics-s1-2026',
    subject: 'الفيزياء',
    title: 'الفيزياء - كتاب الطالب - الصف الثاني عشر - المسار الأكاديمي',
    semester: 'الفصل الدراسي الأول',
    academicYear: currentCurriculumYear,
    publisher: officialSourceLabel,
    status: 'مفهرس بمطابقة حديثة',
    note: 'وجود الكتاب مؤكد في صفحة المركز 2026-2027، وفُهرست وحداته وفق فهرس الخطة الجديدة مع إبقاء مستوى التحقق ظاهرًا للمستخدم.',
  ),
  CurriculumSource(
    id: 'nccd-g12-bio-s1-2026',
    subject: 'الأحياء',
    title: 'العلوم الحياتية - كتاب الطالب - الصف الثاني عشر - المسار الأكاديمي',
    semester: 'الفصل الدراسي الأول',
    academicYear: currentCurriculumYear,
    publisher: officialSourceLabel,
    status: 'مفهرس بمطابقة حديثة',
    note: 'وجود الكتاب مؤكد في صفحة المركز 2026-2027، وفُهرست وحداته وفق فهرس الخطة الجديدة مع إبقاء مستوى التحقق ظاهرًا للمستخدم.',
  ),
];

const curriculumUnits = <CurriculumUnit>[
  CurriculumUnit(
    subject: 'اللغة الإنجليزية',
    number: 1,
    title: 'Identity',
    sourceId: 'nccd-g12-en-s1-2026',
    lessons: [
      'Personality vocabulary',
      'Continuous and perfect tenses',
      'Listening: genes and personality',
      'Reading: language and the world',
      'Writing: a blog post about the past',
    ],
  ),
  CurriculumUnit(
    subject: 'اللغة الإنجليزية',
    number: 2,
    title: 'On the move',
    sourceId: 'nccd-g12-en-s1-2026',
    lessons: [
      'Movement and travel vocabulary',
      'Inversion and cleft sentences',
      'Public transport vocabulary',
      'Considering and comparing alternatives',
      'Writing: an email of complaint',
    ],
  ),
  CurriculumUnit(
    subject: 'اللغة الإنجليزية',
    number: 3,
    title: 'Hard sell',
    sourceId: 'nccd-g12-en-s1-2026',
    lessons: [
      'Business vocabulary',
      'The Passive',
      'Persuasion and attitude',
      'Economics and shopping vocabulary',
      'Writing: a for-and-against essay',
    ],
  ),
  CurriculumUnit(
    subject: 'اللغة الإنجليزية',
    number: 4,
    title: 'Tastes',
    sourceId: 'nccd-g12-en-s1-2026',
    lessons: [
      'Food adjectives and partitives',
      'Advanced conditional structures',
      'Verbs related to senses and eating',
      'Table manners',
      'Writing: a restaurant review',
    ],
  ),
  CurriculumUnit(
    subject: 'اللغة الإنجليزية',
    number: 5,
    title: 'Do your best',
    sourceId: 'nccd-g12-en-s1-2026',
    lessons: [
      'Study idioms and collocations',
      'Modal and related verbs',
      'Sporting success and motivation',
      'Dependent prepositions',
      'Writing: an essay',
    ],
  ),
  CurriculumUnit(
    subject: 'الكيمياء',
    number: 1,
    title: 'حالات المادة',
    sourceId: 'nccd-g12-chem-s1-2026',
    lessons: ['الحالة الغازية', 'الحالة السائلة', 'الحالة الصلبة'],
  ),
  CurriculumUnit(
    subject: 'الكيمياء',
    number: 2,
    title: 'المحاليل',
    sourceId: 'nccd-g12-chem-s1-2026',
    lessons: ['تصنيف المحاليل', 'خصائص المحاليل'],
  ),
  CurriculumUnit(
    subject: 'الكيمياء',
    number: 3,
    title: 'الاتزان الكيميائي',
    sourceId: 'nccd-g12-chem-s1-2026',
    lessons: ['الاتزان الكيميائي والعوامل المؤثرة فيه', 'تعبيرات ثابت الاتزان والحسابات المتعلقة به'],
  ),
  CurriculumUnit(
    subject: 'الكيمياء',
    number: 4,
    title: 'الحموض والقواعد وتطبيقاتها',
    sourceId: 'nccd-g12-chem-s1-2026',
    lessons: [
      'الحموض والقواعد',
      'الرقم الهيدروجيني ومحاليل الحموض والقواعد القوية',
      'محاليل الحموض والقواعد الضعيفة',
      'الأملاح والأيون المشترك',
    ],
  ),
];

const officialCurriculumQuestions = <ExamQuestion>[
  // ---------------------------------------------------------------------------
  // English - Unit 1: Identity
  // ---------------------------------------------------------------------------
  ExamQuestion(
    id: 'nccd-en-u1-01', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Continuous and perfect tenses', difficulty: 'متوسط', skill: 'قواعد',
    text: 'Choose the correct form: “I ________ this book for two hours, and I still have three chapters left.”',
    options: ['have read', 'have been reading', 'am reading', 'had read'], correctIndex: 1,
    explanation: 'Present Perfect Continuous emphasizes an activity continuing over a period up to now.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u1-02', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Continuous and perfect tenses', difficulty: 'متوسط', skill: 'قواعد',
    text: 'By the end of next month, Rami ________ at the company for ten years.',
    options: ['works', 'will work', 'will have been working', 'has worked'], correctIndex: 2,
    explanation: 'Future Perfect Continuous is used for duration continuing up to a future point.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u1-03', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Personality vocabulary', difficulty: 'سهل', skill: 'مفردات',
    text: 'A person who is determined and does not easily change their opinion can best be described as ________.',
    options: ['laid-back', 'strong-willed', 'absent-minded', 'narrow-minded'], correctIndex: 1,
    explanation: 'Strong-willed describes someone determined and firm in their decisions.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u1-04', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Personality vocabulary', difficulty: 'متوسط', skill: 'مفردات',
    text: 'Which expression means “to value something very highly”?',
    options: ['set great store by', 'get a kick out of', 'plump for', 'check out'], correctIndex: 0,
    explanation: 'To set great store by something means to consider it very important or valuable.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u1-05', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Verbs for thinking and understanding', difficulty: 'متوسط', skill: 'استخدام اللغة',
    text: 'Choose the most suitable verb: “It took me a while to ________ what the speaker really meant.”',
    options: ['grasp', 'wander', 'commute', 'persuade'], correctIndex: 0,
    explanation: 'Grasp can mean understand an idea or meaning.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  // Unit 2
  ExamQuestion(
    id: 'nccd-en-u2-01', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Inversion and cleft sentences', difficulty: 'صعب', skill: 'قواعد',
    text: 'Choose the grammatically correct sentence.',
    options: ['Never I had seen such traffic.', 'Never had I seen such traffic.', 'Never I saw such traffic.', 'Never did I had seen such traffic.'], correctIndex: 1,
    explanation: 'After a negative adverbial such as Never at the beginning, auxiliary-subject inversion is required.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u2-02', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Inversion and cleft sentences', difficulty: 'متوسط', skill: 'قواعد',
    text: 'Complete the cleft sentence: “It was the cancelled flight ________ caused the biggest delay.”',
    options: ['who', 'where', 'that', 'what'], correctIndex: 2,
    explanation: 'An it-cleft commonly uses that to focus on a thing or event.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u2-03', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Movement and travel vocabulary', difficulty: 'سهل', skill: 'مفردات',
    text: 'Which verb most directly means “travel regularly between home and work or school”?',
    options: ['commute', 'stroll', 'drift', 'crawl'], correctIndex: 0,
    explanation: 'Commute means to travel regularly between home and a place of work or study.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u2-04', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Considering and comparing alternatives', difficulty: 'متوسط', skill: 'وظائف لغوية',
    text: 'Which sentence best introduces a comparison between two travel options?',
    options: ['There is no point mentioning cost.', 'Compared with the bus, the train is considerably faster.', 'I completely disagree with travelling.', 'The journey has already finished.'], correctIndex: 1,
    explanation: 'Compared with is an appropriate structure for explicitly comparing alternatives.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u2-05', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Writing: an email of complaint', difficulty: 'متوسط', skill: 'كتابة',
    text: 'Which opening is most appropriate for a formal complaint email?',
    options: ['Hey! Your service was terrible.', 'I am writing to express my dissatisfaction with the service I received.', 'Guess what happened to me yesterday!', 'You won’t believe how bad this was!'], correctIndex: 1,
    explanation: 'A formal complaint should use clear, polite and appropriately formal language.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  // Unit 3
  ExamQuestion(
    id: 'nccd-en-u3-01', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'The Passive', difficulty: 'متوسط', skill: 'قواعد',
    text: 'Choose the correct passive form: “The company ________ for misleading customers last year.”',
    options: ['fined', 'was fined', 'has fine', 'was fining'], correctIndex: 1,
    explanation: 'Past Simple Passive is formed with was/were + past participle.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u3-02', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'The Passive', difficulty: 'صعب', skill: 'قواعد',
    text: 'Which sentence correctly reports a general belief using the passive?',
    options: ['The product believes to be safe.', 'It is believed that the product is safe.', 'It believes the product to be safe.', 'The product is believe that safe.'], correctIndex: 1,
    explanation: 'Impersonal passive reporting can use “It is believed that …”.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u3-03', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'Business vocabulary', difficulty: 'متوسط', skill: 'مفردات',
    text: 'A word formed from two nouns and used as one business term, such as “market research”, is a ________.',
    options: ['compound noun', 'phrasal verb', 'conditional clause', 'partitive'], correctIndex: 0,
    explanation: 'Market research is a compound noun made from two words functioning together as one noun phrase.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u3-04', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'Persuasion and attitude', difficulty: 'متوسط', skill: 'فهم',
    text: 'Which adjective most clearly expresses a negative attitude toward an argument that is not convincing?',
    options: ['persuasive', 'compelling', 'unconvincing', 'objective'], correctIndex: 2,
    explanation: 'Unconvincing means not able to make someone believe that something is true or right.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u3-05', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'Writing: a for-and-against essay', difficulty: 'متوسط', skill: 'كتابة',
    text: 'Which connector is most suitable for introducing a contrasting argument in a for-and-against essay?',
    options: ['Furthermore', 'For example', 'However', 'Therefore'], correctIndex: 2,
    explanation: 'However signals contrast and is commonly used to introduce an opposing point.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  // Unit 4
  ExamQuestion(
    id: 'nccd-en-u4-01', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Advanced conditional structures', difficulty: 'صعب', skill: 'قواعد',
    text: 'Choose the correct inverted conditional: “________ I known about the allergy, I would not have ordered that dish.”',
    options: ['Had', 'Were', 'Should', 'Did'], correctIndex: 0,
    explanation: 'Third conditional inversion replaces “If I had known” with “Had I known”.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u4-02', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Advanced conditional structures', difficulty: 'متوسط', skill: 'قواعد',
    text: '“Were the restaurant closer, we ________ there more often.”',
    options: ['eat', 'would eat', 'will eat', 'had eaten'], correctIndex: 1,
    explanation: 'Were + subject expresses an inverted second conditional, followed by would + base verb.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u4-03', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Food adjectives and partitives', difficulty: 'سهل', skill: 'مفردات',
    text: 'Which phrase is a correct partitive?',
    options: ['a slice of bread', 'a bread of slice', 'a piece bread', 'a loaf slice'], correctIndex: 0,
    explanation: 'A slice of bread is a standard partitive expression.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u4-04', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Verbs related to senses and eating', difficulty: 'متوسط', skill: 'مفردات',
    text: 'Which verb best describes eating something slowly in small bites?',
    options: ['devour', 'nibble', 'gulp', 'swallow'], correctIndex: 1,
    explanation: 'Nibble means to take small bites of food.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u4-05', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Writing: a restaurant review', difficulty: 'متوسط', skill: 'كتابة',
    text: 'Which sentence is most suitable in a restaurant review?',
    options: ['The experiment proves the hypothesis.', 'The main character changes dramatically.', 'The service was attentive, although the portions were rather small.', 'The train departs at seven.'], correctIndex: 2,
    explanation: 'A restaurant review evaluates elements such as service, food, atmosphere and value.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  // Unit 5
  ExamQuestion(
    id: 'nccd-en-u5-01', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Modal and related verbs', difficulty: 'متوسط', skill: 'قواعد',
    text: 'You ________ have told me earlier; I could have helped you prepare.',
    options: ['should', 'must', 'can', 'will'], correctIndex: 0,
    explanation: 'Should have + past participle expresses criticism or regret about a past action.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u5-02', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Modal and related verbs', difficulty: 'صعب', skill: 'قواعد',
    text: 'The lights are off and the door is locked. They ________ have gone home already.',
    options: ['must', 'should not', 'cannot', 'need'], correctIndex: 0,
    explanation: 'Must have + past participle expresses a strong logical deduction about the past.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u5-03', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Study idioms and collocations', difficulty: 'متوسط', skill: 'مفردات',
    text: 'Which collocation is natural in English?',
    options: ['make an effort', 'do an effort', 'build an effort', 'take an effort'], correctIndex: 0,
    explanation: 'Make an effort is the standard collocation.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u5-04', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Dependent prepositions', difficulty: 'متوسط', skill: 'استخدام اللغة',
    text: 'Choose the correct preposition: “She succeeded ________ improving her study routine.”',
    options: ['at', 'in', 'on', 'for'], correctIndex: 1,
    explanation: 'The verb succeed is followed by in + -ing form.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-en-u5-05', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Sporting success and motivation', difficulty: 'سهل', skill: 'فهم',
    text: 'Which action is most closely associated with maintaining motivation?',
    options: ['setting achievable goals', 'avoiding all feedback', 'ignoring progress', 'changing targets every hour'], correctIndex: 0,
    explanation: 'Achievable goals make progress visible and can support sustained motivation.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  // ---------------------------------------------------------------------------
  // Chemistry - Unit 1: States of Matter
  // ---------------------------------------------------------------------------
  ExamQuestion(
    id: 'nccd-chem-u1-01', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة الغازية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'أي وصف يفسر قابلية الغاز للانضغاط بدرجة كبيرة مقارنة بالسائل؟',
    options: ['جسيماته كبيرة الحجم', 'المسافات بين جسيماته كبيرة', 'قوى التجاذب فيه شديدة جداً', 'جسيماته ثابتة في مواقعها'], correctIndex: 1,
    explanation: 'وجود فراغات كبيرة بين جسيمات الغاز يسمح بتقليل حجم الغاز عند زيادة الضغط.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u1-02', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة الغازية', difficulty: 'متوسط', skill: 'تطبيق',
    text: 'عند ثبوت الضغط، إذا ارتفعت درجة حرارة كمية من الغاز المثالي بالكلفن فإن حجمه يتوقع أن:',
    options: ['يقل', 'يزداد', 'يبقى ثابتاً', 'يصبح صفراً'], correctIndex: 1,
    explanation: 'وفق قانون شارل، الحجم يتناسب طردياً مع درجة الحرارة المطلقة عند ثبوت الضغط.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u1-03', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة السائلة', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'أي خاصية للسائل تزداد عادةً بزيادة قوة التجاذب بين جزيئاته؟',
    options: ['ضغط البخار', 'سرعة التبخر', 'درجة الغليان', 'قابلية الانضغاط'], correctIndex: 2,
    explanation: 'كلما زادت قوى التجاذب احتاجت الجزيئات إلى طاقة أكبر للانفصال، فترتفع درجة الغليان.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u1-04', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة الصلبة', difficulty: 'متوسط', skill: 'تصنيف',
    text: 'المادة الصلبة التي لا تمتلك ترتيباً بعيد المدى لجسيماتها تُصنّف غالباً بأنها:',
    options: ['بلورية', 'غير بلورية', 'غازية', 'أيونية بالضرورة'], correctIndex: 1,
    explanation: 'المواد الصلبة غير البلورية تفتقر إلى الانتظام طويل المدى المميز للبلورات.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u1-05', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة الصلبة', difficulty: 'صعب', skill: 'استنتاج',
    text: 'مادة صلبة ذات درجة انصهار مرتفعة وتوصل الكهرباء عند انصهارها لا وهي صلبة. أي نوع بلوري هو الأكثر احتمالاً؟',
    options: ['جزيئي', 'أيوني', 'فلزي', 'تساهمي شبكي موصل دائماً'], correctIndex: 1,
    explanation: 'البلورات الأيونية لا توصل في الحالة الصلبة لثبات الأيونات، لكنها توصل عند الانصهار لحركة الأيونات.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  // Unit 2 Solutions
  ExamQuestion(
    id: 'nccd-chem-u2-01', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'تصنيف المحاليل', difficulty: 'سهل', skill: 'تصنيف',
    text: 'المحلول الذي يستطيع إذابة كمية إضافية من المذاب عند درجة حرارة محددة يسمى:',
    options: ['مشبعاً', 'غير مشبع', 'فوق مشبع', 'معلقاً'], correctIndex: 1,
    explanation: 'المحلول غير المشبع يحتوي كمية مذاب أقل من الحد الأقصى الممكن عند الظروف نفسها.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u2-02', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'خصائص المحاليل', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'أي من الآتي يُعد خاصية جامعة للمحاليل؟',
    options: ['لون المحلول', 'خفض درجة التجمد', 'نوع الرابطة داخل المذاب', 'كتلة جزيء المذيب'], correctIndex: 1,
    explanation: 'الخواص الجامعة تعتمد أساساً على عدد جسيمات المذاب، ومنها خفض درجة التجمد.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u2-03', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'خصائص المحاليل', difficulty: 'متوسط', skill: 'تطبيق',
    text: 'إضافة مذاب غير متطاير إلى مذيب نقي تؤدي غالباً إلى:',
    options: ['رفع ضغط البخار', 'خفض درجة الغليان', 'خفض ضغط البخار', 'عدم تغير أي خاصية'], correctIndex: 2,
    explanation: 'وجود المذاب غير المتطاير يقلل الكسر المولي للمذيب ويخفض ضغط بخاره.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u2-04', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'تصنيف المحاليل', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'إذا وُجدت كمية من المذاب غير الذائب في قاع الوعاء عند ثبات درجة الحرارة، فإن المحلول فوقه غالباً:',
    options: ['غير مشبع', 'مشبع', 'مخفف بالضرورة', 'غازي'], correctIndex: 1,
    explanation: 'بقاء مذاب صلب غير ذائب عند الاتزان يدل عادةً على وصول المحلول إلى حد الإشباع.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u2-05', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'خصائص المحاليل', difficulty: 'صعب', skill: 'مقارنة',
    text: 'عند تساوي التركيز، أي محلول يُتوقع أن يُحدث أثراً جامعاً أكبر إذا تفكك المذاب كلياً؟',
    options: ['مذاب لا يتأين', 'مذاب ينتج أيونين', 'مذاب ينتج ثلاثة أيونات', 'جميعها متساوية'], correctIndex: 2,
    explanation: 'الأثر الجامع يزداد بزيادة عدد الجسيمات الناتجة في المحلول عند التركيز نفسه.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  // Unit 3 Equilibrium
  ExamQuestion(
    id: 'nccd-chem-u3-01', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'عند الاتزان الكيميائي الديناميكي في نظام مغلق تكون:',
    options: ['تراكيز المواد كلها متساوية', 'سرعة التفاعل الأمامي مساوية لسرعة التفاعل العكسي', 'التفاعلات قد توقفت', 'كمية النواتج صفراً'], correctIndex: 1,
    explanation: 'الاتزان ديناميكي؛ يستمر التفاعلان الأمامي والعكسي بسرعتين متساويتين.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u3-02', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'لنظام غازي متزن، زيادة الضغط بخفض الحجم تدفع الاتزان عادةً نحو الطرف الذي يحتوي:',
    options: ['عدد مولات غازية أكبر', 'عدد مولات غازية أقل', 'كتلة أكبر فقط', 'درجة حرارة أعلى'], correctIndex: 1,
    explanation: 'وفق مبدأ لوشاتلييه، النظام يقاوم زيادة الضغط بالاتجاه نحو عدد أقل من مولات الغاز.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u3-03', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'تعبيرات ثابت الاتزان والحسابات المتعلقة به', difficulty: 'متوسط', skill: 'حسابات',
    text: 'في تعبير Kc لتفاعل متزن، ما الذي يحدث لمعاملات المعادلة الموزونة؟',
    options: ['تهمل جميعاً', 'تظهر كأسس لتراكيز المواد', 'تضاف إلى التراكيز', 'تضرب في درجة الحرارة'], correctIndex: 1,
    explanation: 'معامل كل مادة في المعادلة الموزونة يصبح أساً لتركيزها في تعبير ثابت الاتزان.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u3-04', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'إضافة عامل حفاز إلى نظام متزن تؤدي إلى:',
    options: ['زيادة قيمة Kc', 'إزاحة الاتزان نحو النواتج', 'الوصول إلى الاتزان بسرعة أكبر دون تغيير موضعه', 'إيقاف التفاعل العكسي'], correctIndex: 2,
    explanation: 'العامل الحفاز يسرع التفاعلين الأمامي والعكسي ولا يغير ثابت الاتزان أو تركيب الاتزان.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u3-05', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'تعبيرات ثابت الاتزان والحسابات المتعلقة به', difficulty: 'صعب', skill: 'استنتاج',
    text: 'إذا كانت قيمة Kc كبيرة جداً لتفاعل عند درجة حرارة معينة، فهذا يشير غالباً إلى أن الاتزان:',
    options: ['يميل بقوة نحو النواتج', 'يميل بقوة نحو المتفاعلات', 'لا يمكن أن يتحقق', 'يعني تساوي جميع التراكيز'], correctIndex: 0,
    explanation: 'القيمة الكبيرة لـ Kc تعني أن نسبة تراكيز النواتج إلى المتفاعلات في تعبير الاتزان كبيرة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  // Unit 4 Acids and Bases
  ExamQuestion(
    id: 'nccd-chem-u4-01', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الحموض والقواعد', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'وفق مفهوم برونستد-لوري، القاعدة هي مادة:',
    options: ['تمنح بروتوناً', 'تستقبل بروتوناً', 'تمنح إلكتروناً فقط', 'لا تتفاعل مع الماء'], correctIndex: 1,
    explanation: 'قاعدة برونستد-لوري هي مستقبل للبروتون H+.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u4-02', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الرقم الهيدروجيني ومحاليل الحموض والقواعد القوية', difficulty: 'متوسط', skill: 'حسابات',
    text: 'إذا كان تركيز +H3O في محلول يساوي 1×10⁻³ M، فإن قيمة pH تساوي تقريباً:',
    options: ['1', '3', '7', '11'], correctIndex: 1,
    explanation: 'pH = -log[H3O+] = -log(10^-3) = 3.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u4-03', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'محاليل الحموض والقواعد الضعيفة', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'إذا كانت قيمة Ka لحمض ما أكبر من قيمة Ka لحمض آخر عند الظروف نفسها، فالحمض الأول غالباً:',
    options: ['أضعف', 'أقوى', 'متعادل', 'غير قابل للتأين'], correctIndex: 1,
    explanation: 'Ka الأكبر يدل على تأين أكبر للحمض وبالتالي قوة حمضية أعلى.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u4-04', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الأملاح والأيون المشترك', difficulty: 'صعب', skill: 'استنتاج',
    text: 'إضافة ملح يحتوي الأيون المشترك إلى محلول حمض ضعيف تؤدي عادةً إلى:',
    options: ['زيادة تأين الحمض', 'تقليل تأين الحمض', 'عدم تأثير مطلقاً', 'تحويل الحمض إلى حمض قوي'], correctIndex: 1,
    explanation: 'تأثير الأيون المشترك يزيح اتزان تأين الحمض الضعيف نحو الصورة غير المتأينة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u4-05', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الأملاح والأيون المشترك', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'المحلول المنظم يتميز بأنه:',
    options: ['يحافظ نسبياً على pH عند إضافة كميات صغيرة من حمض أو قاعدة', 'يجب أن يكون pH له 7 دائماً', 'يتكون من ماء نقي فقط', 'لا يحتوي أيونات'], correctIndex: 0,
    explanation: 'المحلول المنظم يقاوم التغير الكبير في pH عند إضافة كميات صغيرة من حمض أو قاعدة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u1-06', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة الغازية', difficulty: 'متوسط', skill: 'تطبيق',
    text: 'عند ثبوت درجة الحرارة، إذا تضاعف ضغط كمية محددة من الغاز المثالي، فإن حجمها يصبح تقريباً:',
    options: ['ضعفين', 'نصف الحجم الأصلي', 'أربعة أضعاف', 'لا يتغير'], correctIndex: 1,
    explanation: 'وفق قانون بويل، الضغط والحجم يتناسبان عكسياً عند ثبوت درجة الحرارة وكمية الغاز.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u2-06', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'خصائص المحاليل', difficulty: 'متوسط', skill: 'حسابات',
    text: 'أي تعبير يصف المولالية بصورة صحيحة؟',
    options: ['مولات المذاب لكل لتر من المحلول', 'مولات المذاب لكل كيلوجرام من المذيب', 'جرامات المذيب لكل مول من المذاب', 'مولات المذيب لكل لتر من المذاب'], correctIndex: 1,
    explanation: 'المولالية هي عدد مولات المذاب مقسوماً على كتلة المذيب بالكيلوجرام.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u3-06', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه', difficulty: 'صعب', skill: 'استنتاج',
    text: 'في تفاعل طارد للحرارة عند الاتزان، رفع درجة الحرارة يدفع الاتزان غالباً نحو:',
    options: ['النواتج', 'المتفاعلات', 'لا يحدث أي تغير', 'زيادة قيمة العامل الحفاز'], correctIndex: 1,
    explanation: 'في التفاعل الطارد تعد الحرارة ناتجاً؛ إضافتها تدفع النظام في الاتجاه العكسي وفق مبدأ لوشاتلييه.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u4-06', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الحموض والقواعد', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'في الزوج المترافق NH4+/NH3، تُعد NH3 بالنسبة إلى NH4+:',
    options: ['حمضاً مرافقاً', 'قاعدة مرافقة', 'ملحاً متعادلاً', 'عاملاً مؤكسداً'], correctIndex: 1,
    explanation: 'تنتج NH3 من NH4+ بعد فقد بروتون، لذلك فهي القاعدة المرافقة له.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'nccd-chem-u4-07', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الرقم الهيدروجيني ومحاليل الحموض والقواعد القوية', difficulty: 'صعب', skill: 'حسابات',
    text: 'عند 25°C، إذا كانت قيمة pOH لمحلول تساوي 4، فإن قيمة pH تساوي:',
    options: ['4', '7', '10', '14'], correctIndex: 2,
    explanation: 'عند 25°C: pH + pOH = 14، لذا pH = 14 - 4 = 10.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
];

int get verifiedOfficialQuestionCount =>
    officialCurriculumQuestions.where((q) => q.verifiedFromOfficialCurriculum).length;

List<CurriculumUnit> unitsForSubject(String subject) =>
    curriculumUnits.where((unit) => unit.subject == subject).toList(growable: false);

CurriculumSource? sourceById(String id) {
  for (final source in curriculumSources) {
    if (source.id == id) return source;
  }
  return null;
}
