import 'models.dart';

/// V11 supplements the verified curriculum bank so every 2026-style mock can
/// draw 40 book-grounded items + 10 transfer/application items per subject.
///
/// Transfer items use new contexts/numbers but test only skills and concepts
/// that are present in the official Grade 12 books. They are never labelled as
/// verbatim ministry/textbook questions.
const v11MinisterialSupplementQuestions = <ExamQuestion>[
  // -------------------------------------------------------------------------
  // ENGLISH ADVANCED — TRANSFER / APPLICATION (10)
  // -------------------------------------------------------------------------
  ExamQuestion(
    id: 'v11-en-tr-01', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Continuous and perfect tenses', skill: 'استخدام اللغة', difficulty: 'متوسط',
    text: 'Maya looks exhausted because she ______ for the interview since early morning.',
    options: ['has prepared', 'has been preparing', 'was preparing', 'had prepared'],
    correctIndex: 1,
    explanation: 'The activity started earlier and has continued up to the present result, so the present perfect continuous is the best choice.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 1 Identity – Continuous and perfect tenses',
    tawjihiStyleYear: '2026', distractorDesign: 'أزمنة قريبة وظيفيًا مع فرق في الاستمرار والنتيجة',
  ),
  ExamQuestion(
    id: 'v11-en-tr-02', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Inversion and cleft sentences', skill: 'قواعد متقدمة', difficulty: 'صعب',
    text: 'Choose the sentence that is grammatically correct.',
    options: ['Rarely I have seen such crowded roads.', 'Rarely have I seen such crowded roads.', 'Rarely I saw such crowded roads.', 'Rarely did I have seen such crowded roads.'],
    correctIndex: 1,
    explanation: 'A negative/limiting adverb at the beginning triggers subject–auxiliary inversion.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 2 On the move – Inversion',
    tawjihiStyleYear: '2026', distractorDesign: 'مشتتات تمثل أخطاء ترتيب الفاعل والفعل المساعد',
  ),
  ExamQuestion(
    id: 'v11-en-tr-03', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'The Passive', skill: 'قواعد', difficulty: 'متوسط',
    text: 'A new shopping app ______ by the company next month.',
    options: ['will launch', 'will be launched', 'is launching', 'has launched'],
    correctIndex: 1,
    explanation: 'The app receives the action, so the future passive form is required.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 3 Hard sell – The Passive',
    tawjihiStyleYear: '2026', distractorDesign: 'فاعل/مفعول وزمن متقارب',
  ),
  ExamQuestion(
    id: 'v11-en-tr-04', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Advanced conditional structures', skill: 'قواعد متقدمة', difficulty: 'صعب',
    text: 'Had the restaurant checked the booking list, the guests ______ outside for twenty minutes.',
    options: ['would not wait', 'would not have waited', 'will not have waited', 'did not wait'],
    correctIndex: 1,
    explanation: 'Had + past participle is an inverted third conditional; the result uses would have + past participle.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 4 Tastes – Advanced conditionals',
    tawjihiStyleYear: '2026', distractorDesign: 'خلط مقصود بين أنواع الشرط',
  ),
  ExamQuestion(
    id: 'v11-en-tr-05', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Modal and related verbs', skill: 'استخدام اللغة', difficulty: 'متوسط',
    text: 'You ______ have told me about the deadline earlier; now there is almost no time left.',
    options: ['should', 'must', 'can', 'might'],
    correctIndex: 0,
    explanation: 'Should have + past participle expresses criticism or regret about a past action.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 5 Do your best – Modal and related verbs',
    tawjihiStyleYear: '2026', distractorDesign: 'دلالات modal متقاربة',
  ),
  ExamQuestion(
    id: 'v11-en-tr-06', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Personality vocabulary', skill: 'مفردات في السياق', difficulty: 'متوسط',
    text: 'Although Lena disagreed with the proposal, she listened carefully to both sides. She was being ______.',
    options: ['strong-willed', 'open-minded', 'laid-back', 'sentimental'],
    correctIndex: 1,
    explanation: 'Open-minded describes someone willing to consider different ideas or opinions.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 1 Identity – Personality vocabulary',
    tawjihiStyleYear: '2026', distractorDesign: 'كل البدائل صفات شخصية من الحقل نفسه',
  ),
  ExamQuestion(
    id: 'v11-en-tr-07', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'Persuasion and attitude', skill: 'استنتاج المعنى', difficulty: 'متقدم',
    text: 'An advert says, “Only 3 rooms left at this price.” The technique mainly tries to persuade customers by creating a sense of ______.',
    options: ['scarcity', 'neutrality', 'long-term stability', 'technical precision'],
    correctIndex: 0,
    explanation: 'Limited availability creates scarcity and urgency, a common persuasive technique.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 3 Hard sell – Persuasion',
    tawjihiStyleYear: '2026', distractorDesign: 'خيارات مفاهيمية قريبة من تحليل الإعلان',
  ),
  ExamQuestion(
    id: 'v11-en-tr-08', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Considering and comparing alternatives', skill: 'وظائف لغوية', difficulty: 'سهل',
    text: 'Which sentence best introduces a balanced comparison between two travel options?',
    options: ['This one is obviously perfect.', 'Whereas the train is faster, the coach is cheaper.', 'You must choose the train.', 'Neither option has any advantage.'],
    correctIndex: 1,
    explanation: 'Whereas explicitly contrasts two alternatives in a balanced way.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 2 On the move – Comparing alternatives',
    tawjihiStyleYear: '2026', distractorDesign: 'تمييز الوظيفة اللغوية لا القاعدة فقط',
  ),
  ExamQuestion(
    id: 'v11-en-tr-09', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Writing: a restaurant review', skill: 'كتابة واستنتاج', difficulty: 'متوسط',
    text: 'Which sentence is most appropriate in the recommendation section of a restaurant review?',
    options: ['The waiter had arrived at seven.', 'I would definitely recommend it for a relaxed family meal.', 'Food is a general word.', 'The kitchen was built in 2019.'],
    correctIndex: 1,
    explanation: 'A review conclusion normally evaluates the experience and gives a recommendation.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 4 Tastes – Restaurant review',
    tawjihiStyleYear: '2026', distractorDesign: 'اختيار الجملة الأنسب للغرض الكتابي',
  ),
  ExamQuestion(
    id: 'v11-en-tr-10', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Study idioms and collocations', skill: 'مفردات في السياق', difficulty: 'متوسط',
    text: 'After several failed attempts, the research team finally ______ a solution that worked.',
    options: ['came up with', 'looked down on', 'ran out of', 'put off'],
    correctIndex: 0,
    explanation: 'Come up with means produce or think of an idea/solution.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027',
    verifiedFromOfficialCurriculum: true, questionOrigin: 'transfer',
    sourceReference: 'High Note 12 S1 – Unit 5 Do your best – Study language/collocations',
    tawjihiStyleYear: '2026', distractorDesign: 'phrasal verbs plausible in form but wrong in meaning',
  ),

  // -------------------------------------------------------------------------
  // CHEMISTRY — TRANSFER / APPLICATION (10)
  // -------------------------------------------------------------------------
  ExamQuestion(
    id: 'v11-ch-tr-01', subject: 'الكيمياء', unit: 'حالات المادة', lesson: 'الحالة الغازية',
    skill: 'حسابات الغازات', difficulty: 'متوسط',
    text: 'غاز حجمه 2.0 L عند ضغط 1.0 atm. إذا أصبح الضغط 4.0 atm عند ثبوت درجة الحرارة، فما الحجم الجديد؟',
    options: ['0.50 L', '2.0 L', '4.0 L', '8.0 L'], correctIndex: 0,
    explanation: 'من قانون بويل P1V1=P2V2، إذن V2=(1×2)/4=0.50 L.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – حالات المادة – قوانين الغازات', tawjihiStyleYear: '2026',
    distractorDesign: 'أخطاء التناسب العكسي وعدم تحويل العلاقة',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-02', subject: 'الكيمياء', unit: 'حالات المادة', lesson: 'الحالة الغازية',
    skill: 'الضغوط الجزئية', difficulty: 'متوسط',
    text: 'خليط غازي غير متفاعل ضغوط مكوناته الجزئية 0.40 و0.35 و0.25 atm. الضغط الكلي للخليط يساوي:',
    options: ['0.40 atm', '0.75 atm', '1.00 atm', '1.40 atm'], correctIndex: 2,
    explanation: 'بحسب قانون دالتون، الضغط الكلي يساوي مجموع الضغوط الجزئية = 1.00 atm.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – الحالة الغازية – قانون دالتون', tawjihiStyleYear: '2026',
    distractorDesign: 'الجمع الجزئي أو اختيار أكبر ضغط',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-03', subject: 'الكيمياء', unit: 'المحاليل', lesson: 'تصنيف المحاليل',
    skill: 'فهم المحاليل', difficulty: 'سهل',
    text: 'محلول يحتوي أقصى كمية يمكن أن تذوب من المذاب عند درجة حرارة محددة يسمى:',
    options: ['غير مشبع', 'مشبع', 'فوق مشبع دائمًا', 'غروي'], correctIndex: 1,
    explanation: 'المحلول المشبع يحتوي الكمية القصوى من المذاب عند شروط محددة.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – المحاليل – تصنيف المحاليل', tawjihiStyleYear: '2026', distractorDesign: 'مصطلحات من الوحدة نفسها',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-04', subject: 'الكيمياء', unit: 'المحاليل', lesson: 'خصائص المحاليل',
    skill: 'تطبيق خصائص المحاليل', difficulty: 'صعب',
    text: 'أضيفت الكمية نفسها من NaCl إلى 100 mL ماء في كأسين، لكن أحدهما عند درجة حرارة أعلى. إذا كان الذوبان ماصًا للحرارة، فأي توقع هو الأفضل؟',
    options: ['تنخفض الذائبية دائمًا مع الحرارة', 'قد تزداد كمية المذاب القابلة للذوبان في الكأس الأدفأ', 'لا تؤثر الحرارة مطلقًا في الذائبية', 'يتحول المذاب إلى غاز حتمًا'], correctIndex: 1,
    explanation: 'في عملية ذوبان ماصة للحرارة، رفع درجة الحرارة يمكن أن يزيد الذائبية وفق مبدأ لوشاتيليه.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – المحاليل – خصائص المحاليل', tawjihiStyleYear: '2026', distractorDesign: 'تعميمات خاطئة شائعة حول الحرارة والذائبية',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-05', subject: 'الكيمياء', unit: 'الاتزان الكيميائي', lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه',
    skill: 'مبدأ لوشاتيليه', difficulty: 'متوسط',
    text: 'في نظام متزن A(g)+B(g) ⇌ C(g)، أضيفت كمية من A عند ثبوت الحرارة. مباشرة بعد الإضافة، يميل النظام إلى:',
    options: ['الاتجاه نحو المتفاعلات', 'الاتجاه نحو تكوين C', 'تغيير قيمة Kc', 'التوقف عن التفاعل'], correctIndex: 1,
    explanation: 'يزاح الاتزان لاستهلاك الزيادة في A، بينما Kc لا تتغير ما دامت الحرارة ثابتة.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – الاتزان – العوامل المؤثرة', tawjihiStyleYear: '2026', distractorDesign: 'الخلط بين موضع الاتزان وقيمة ثابت الاتزان',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-06', subject: 'الكيمياء', unit: 'الاتزان الكيميائي', lesson: 'تعبيرات ثابت الاتزان والحسابات المتعلقة به',
    skill: 'تعبير Kc', difficulty: 'متوسط',
    text: 'للتفاعل N2(g)+3H2(g) ⇌ 2NH3(g)، أي تعبير يمثل Kc بصورة صحيحة؟',
    options: ['[NH3]²/([N2][H2]³)', '[N2][H2]³/[NH3]²', '[NH3]/([N2][H2])', '[NH3]²/([N2]³[H2])'], correctIndex: 0,
    explanation: 'تراكيز النواتج في البسط والمتفاعلات في المقام، والأسس تساوي المعاملات الستوكيومترية.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – الاتزان – تعبيرات ثابت الاتزان', tawjihiStyleYear: '2026', distractorDesign: 'عكس الكسر وتبديل الأسس',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-07', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها', lesson: 'الرقم الهيدروجيني ومحاليل الحموض والقواعد القوية',
    skill: 'حساب pH', difficulty: 'متوسط',
    text: 'إذا كان تركيز H3O+ في محلول يساوي 1.0×10⁻⁴ M، فإن pH يساوي:',
    options: ['4', '10', '–4', '1×10⁻⁴'], correctIndex: 0,
    explanation: 'pH = –log[H3O+] = 4.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – الحموض والقواعد – الرقم الهيدروجيني', tawjihiStyleYear: '2026', distractorDesign: 'قيمة الأس، pOH، وترك التركيز دون تحويل',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-08', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها', lesson: 'محاليل الحموض والقواعد الضعيفة',
    skill: 'قوة الحمض', difficulty: 'صعب',
    text: 'لحمضين ضعيفين HA وHB بالتركيز نفسه، إذا كانت Ka للحمض HA أكبر، فأي عبارة أدق؟',
    options: ['HA أضعف وpH له أعلى', 'HA أقوى و[H3O+] له أكبر', 'HB يتأين كليًا', 'لهما pH نفسه حتمًا'], correctIndex: 1,
    explanation: 'Ka الأكبر تدل على تأين أكبر وحمض أقوى نسبيًا، فينتج تركيز H3O+ أكبر عند التركيز نفسه.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – الحموض الضعيفة – Ka', tawjihiStyleYear: '2026', distractorDesign: 'عكس علاقة Ka بالقوة وpH',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-09', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها', lesson: 'الأملاح والأيون المشترك',
    skill: 'الأيون المشترك', difficulty: 'متقدم',
    text: 'إضافة ملح يحتوي الأيون A⁻ إلى محلول الحمض الضعيف HA تؤدي غالبًا إلى:',
    options: ['زيادة تأين HA', 'تقليل تأين HA', 'عدم تأثر الاتزان إطلاقًا', 'زيادة Ka'], correctIndex: 1,
    explanation: 'الأيون المشترك A⁻ يزيح اتزان تأين الحمض نحو اليسار، بينما Ka ثابتة عند ثبوت الحرارة.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – الأملاح والأيون المشترك', tawjihiStyleYear: '2026', distractorDesign: 'الخلط بين درجة التأين وثابت التأين',
  ),
  ExamQuestion(
    id: 'v11-ch-tr-10', subject: 'الكيمياء', unit: 'حالات المادة', lesson: 'الحالة الصلبة',
    skill: 'قوى التجاذب والبنية', difficulty: 'متوسط',
    text: 'مادة صلبة بلورية توصل الكهرباء عند صهرها ولا توصلها وهي صلبة. هذا السلوك يتفق أكثر مع بلورة:',
    options: ['أيونية', 'جزيئية غير قطبية', 'فلزية', 'تساهمية شبكية فقط'], correctIndex: 0,
    explanation: 'الأيونات تكون مقيدة في الشبكة الصلبة وتصبح حرة الحركة عند الانصهار.',
    sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'كيمياء 12 – حالات المادة – الحالة الصلبة', tawjihiStyleYear: '2026', distractorDesign: 'ربط خاصية تجريبية بنوع البلورة',
  ),

  // -------------------------------------------------------------------------
  // MATHEMATICS — 5 BOOK-GROUNDED + 10 TRANSFER
  // -------------------------------------------------------------------------
  ExamQuestion(
    id: 'v11-ma-bk-01', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية', lesson: 'نظريتا الباقي والعوامل', skill: 'نظرية الباقي', difficulty: 'متوسط',
    text: 'إذا كان P(x)=x³−4x+5، فإن باقي قسمة P(x) على (x−2) يساوي:', options: ['1', '5', '8', '13'], correctIndex: 1,
    explanation: 'بحسب نظرية الباقي، الباقي هو P(2)=8−8+5=5.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'رياضيات 12 – الاقترانات والمقادير الجبرية – نظريتا الباقي والعوامل', tawjihiStyleYear: '2026', distractorDesign: 'قيم ناتجة عن تعويض ناقص أو خطأ إشارة',
  ),
  ExamQuestion(
    id: 'v11-ma-bk-02', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية', lesson: 'المتطابقات المثلثية', skill: 'تبسيط مثلثي', difficulty: 'سهل',
    text: 'أي تعبير يساوي 1−sin²θ؟', options: ['cos²θ', 'tan²θ', 'sec²θ', 'sin²θ'], correctIndex: 0,
    explanation: 'من المتطابقة الأساسية sin²θ+cos²θ=1.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'رياضيات 12 – المتطابقات والمعادلات المثلثية', tawjihiStyleYear: '2026', distractorDesign: 'متطابقات مثلثية قريبة',
  ),
  ExamQuestion(
    id: 'v11-ma-bk-03', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته', lesson: 'قاعدة السلسلة', skill: 'اشتقاق', difficulty: 'متوسط',
    text: 'إذا كانت f(x)=(3x+1)⁴، فإن f′(x) تساوي:', options: ['4(3x+1)³', '12(3x+1)³', '12(3x+1)⁴', '3(3x+1)³'], correctIndex: 1,
    explanation: 'قاعدة السلسلة: 4(3x+1)³×3 = 12(3x+1)³.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'رياضيات 12 – التفاضل – قاعدة السلسلة', tawjihiStyleYear: '2026', distractorDesign: 'نسيان مشتقة الداخل أو إبقاء الأس',
  ),
  ExamQuestion(
    id: 'v11-ma-bk-04', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته', lesson: 'الاشتقاق الضمني', skill: 'اشتقاق ضمني', difficulty: 'صعب',
    text: 'إذا كان x²+y²=25، فإن dy/dx يساوي:', options: ['−x/y', 'x/y', '−y/x', '2x+2y'], correctIndex: 0,
    explanation: 'بالتفاضل: 2x+2y y′=0، ومنه y′=−x/y.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'رياضيات 12 – التفاضل – الاشتقاق الضمني', tawjihiStyleYear: '2026', distractorDesign: 'قلب الكسر وخطأ الإشارة وإهمال y′',
  ),
  ExamQuestion(
    id: 'v11-ma-bk-05', subject: 'الرياضيات', unit: 'الأعداد المركبة', lesson: 'العمليات على الأعداد المركبة', skill: 'عمليات مركبة', difficulty: 'متوسط',
    text: 'ناتج (2+3i)(2−3i) يساوي:', options: ['−5', '5', '13', '4−9i'], correctIndex: 2,
    explanation: 'حاصل ضرب العدد ومرافقه يساوي مربع المعيار: 2²+3²=13.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'رياضيات 12 – الأعداد المركبة – العمليات', tawjihiStyleYear: '2026', distractorDesign: 'إهمال i² أو عدم استخدام المرافق',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-01', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية', lesson: 'نظريتا الباقي والعوامل', skill: 'استدلال جبري', difficulty: 'متوسط',
    text: 'صُمم برنامج ليختبر هل (x−3) عامل في P(x). أي قيمة يجب أن يحسبها البرنامج أولًا؟', options: ['P(0)', 'P(1)', 'P(3)', 'P(−3)'], correctIndex: 2,
    explanation: 'بحسب نظرية العوامل، (x−a) عامل إذا كان P(a)=0.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – نظرية العوامل', tawjihiStyleYear: '2026', distractorDesign: 'اختبار فهم معنى a في العامل (x−a)',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-02', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية', lesson: 'الكسور الجزئية', skill: 'تحليل كسور جزئية', difficulty: 'صعب',
    text: 'عند تحليل 1/[(x−1)(x+2)] إلى كسور جزئية، أي صورة ابتدائية صحيحة؟', options: ['A/(x−1)+B/(x+2)', 'A/(x−1)²+B/(x+2)²', 'A/x+B/(x+1)', 'A(x−1)+B(x+2)'], correctIndex: 0,
    explanation: 'لكل عامل خطي مميز في المقام كسر جزئي ثابت البسط.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – الكسور الجزئية', tawjihiStyleYear: '2026', distractorDesign: 'صور تحليل قريبة لكنها لا تطابق نوع العوامل',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-03', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية', lesson: 'حل المعادلات المثلثية', skill: 'حل معادلة مثلثية', difficulty: 'متوسط',
    text: 'إذا كان sinθ=1/2 و0°≤θ≤180°، فإن قيم θ هي:', options: ['30° فقط', '150° فقط', '30° و150°', '60° و120°'], correctIndex: 2,
    explanation: 'الجيب موجب في الربعين الأول والثاني، وزاوية المرجع 30°.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – حل المعادلات المثلثية', tawjihiStyleYear: '2026', distractorDesign: 'نسيان أحد الحلين أو خلط زاوية المرجع',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-04', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته', lesson: 'تطبيقات المشتقة', skill: 'تزايد وتناقص', difficulty: 'متوسط',
    text: 'يمثل f′(x) سرعة تغير كمية ما. إذا كان f′(x)<0 خلال الفترة (2,5)، فما الوصف الأدق للكمية f؟', options: ['تزداد', 'تتناقص', 'تبقى ثابتة', 'لا يمكن معرفة اتجاهها'], correctIndex: 1,
    explanation: 'المشتقة السالبة تعني أن الدالة تتناقص على تلك الفترة.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – تطبيقات المشتقة', tawjihiStyleYear: '2026', distractorDesign: 'ربط إشارة المشتقة بسلوك الدالة',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-05', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته', lesson: 'تطبيقات المشتقة', skill: 'قيم قصوى', difficulty: 'صعب',
    text: 'إذا تغيرت إشارة f′ عند x=4 من سالبة إلى موجبة، فإن x=4 تمثل غالبًا:', options: ['قيمة عظمى محلية', 'قيمة صغرى محلية', 'نقطة لا علاقة لها بالسلوك', 'مقاربًا رأسيًا'], correctIndex: 1,
    explanation: 'الانتقال من التناقص إلى التزايد يدل على قيمة صغرى محلية.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – تطبيقات المشتقة – القيم القصوى', tawjihiStyleYear: '2026', distractorDesign: 'عكس اتجاه تغير إشارة المشتقة',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-06', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته', lesson: 'قواعد الاشتقاق', skill: 'معدل تغير', difficulty: 'متقدم',
    text: 'موضع جسم s(t)=t³−6t²+9t. في أي قيمة t تكون السرعة اللحظية صفرًا؟', options: ['t=1 فقط', 't=3 فقط', 't=1 وt=3', 't=0 وt=6'], correctIndex: 2,
    explanation: 'v(t)=s′(t)=3t²−12t+9=3(t−1)(t−3)، فتساوي صفرًا عند 1 و3.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – التفاضل وتطبيقاته – معدل التغير', tawjihiStyleYear: '2026', distractorDesign: 'حل جزئي أو خلط الموضع بالسرعة',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-07', subject: 'الرياضيات', unit: 'الأعداد المركبة', lesson: 'الأعداد المركبة', skill: 'تمثيل مركب', difficulty: 'سهل',
    text: 'النقطة التي تمثل العدد المركب −2+5i في المستوى المركب هي:', options: ['(−2,5)', '(2,−5)', '(5,−2)', '(−5,2)'], correctIndex: 0,
    explanation: 'الجزء الحقيقي يمثل الإحداثي الأفقي والخيالي معامل i يمثل الإحداثي الرأسي.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – الأعداد المركبة', tawjihiStyleYear: '2026', distractorDesign: 'تبديل الجزأين والإشارات',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-08', subject: 'الرياضيات', unit: 'الأعداد المركبة', lesson: 'العمليات على الأعداد المركبة', skill: 'قوى i', difficulty: 'متوسط',
    text: 'قيمة i²⁷ تساوي:', options: ['1', '−1', 'i', '−i'], correctIndex: 3,
    explanation: 'تتكرر قوى i كل 4؛ 27 mod 4 = 3، لذا i²⁷=i³=−i.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – العمليات على الأعداد المركبة', tawjihiStyleYear: '2026', distractorDesign: 'دورة قوى i',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-09', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية', lesson: 'المتطابقات المثلثية', skill: 'تحويل مثلثي', difficulty: 'متوسط',
    text: 'إذا كان cosθ≠0، فإن sinθ/cosθ يساوي:', options: ['cotθ', 'tanθ', 'secθ', 'cscθ'], correctIndex: 1,
    explanation: 'tanθ=sinθ/cosθ.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – المتطابقات المثلثية', tawjihiStyleYear: '2026', distractorDesign: 'نسب مثلثية متبادلة',
  ),
  ExamQuestion(
    id: 'v11-ma-tr-10', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته', lesson: 'قاعدة السلسلة', skill: 'اشتقاق مركب', difficulty: 'صعب',
    text: 'إذا كانت y=sin(2x)، فإن dy/dx تساوي:', options: ['cos(2x)', '2cos(2x)', '−2sin(2x)', '2sin(2x)'], correctIndex: 1,
    explanation: 'مشتقة sin(u)=cos(u)u′، وu=2x لذا u′=2.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'رياضيات 12 – التفاضل – قاعدة السلسلة', tawjihiStyleYear: '2026', distractorDesign: 'نسيان مشتقة الداخل أو خلط مشتقة الجيب',
  ),

  // -------------------------------------------------------------------------
  // PHYSICS — 5 BOOK-GROUNDED + 10 TRANSFER
  // -------------------------------------------------------------------------
  ExamQuestion(
    id: 'v11-ph-bk-01', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات', lesson: 'الزخم الخطي والدفع', skill: 'الزخم والدفع', difficulty: 'سهل',
    text: 'جسم كتلته 2 kg يتحرك بسرعة 3 m/s. مقدار زخمه الخطي يساوي:', options: ['1.5', '5', '6', '9'], correctIndex: 2,
    explanation: 'p=mv=2×3=6 kg·m/s.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – الزخم الخطي والدفع', tawjihiStyleYear: '2026', distractorDesign: 'قسمة الكتلة على السرعة أو جمعهما',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-02', subject: 'الفيزياء', unit: 'الحركة الدورانية', lesson: 'العزم والاتزان السكوني', skill: 'العزم', difficulty: 'متوسط',
    text: 'يزداد مقدار عزم قوة حول محور عندما:', options: ['يقل ذراع القوة', 'تزداد القوة أو ذراعها العمودي', 'تصبح القوة موازية لذراعها دائمًا', 'تساوي السرعة صفرًا فقط'], correctIndex: 1,
    explanation: 'τ=rF sinθ، لذا يزداد بزيادة القوة أو المسافة العمودية المناسبة.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – الحركة الدورانية – العزم', tawjihiStyleYear: '2026', distractorDesign: 'خلط العزم بالقوة الخطية',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-03', subject: 'الفيزياء', unit: 'الكهرباء السكونية', lesson: 'المجال الكهربائي', skill: 'المجال الكهربائي', difficulty: 'متوسط',
    text: 'اتجاه المجال الكهربائي عند نقطة يُعرَّف بأنه اتجاه القوة المؤثرة في:', options: ['شحنة اختبار موجبة', 'شحنة اختبار سالبة', 'جسم متعادل فقط', 'أي كتلة صغيرة'], correctIndex: 0,
    explanation: 'تعريف اتجاه المجال يعتمد على شحنة اختبار موجبة.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – الكهرباء السكونية – المجال الكهربائي', tawjihiStyleYear: '2026', distractorDesign: 'عكس اتجاه الشحنة الاختبارية',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-04', subject: 'الفيزياء', unit: 'التيار الكهربائي', lesson: 'المقاومة والقوة الدافعة الكهربائية', skill: 'قانون أوم', difficulty: 'متوسط',
    text: 'فرق جهد 12 V بين طرفي مقاومة 4 Ω. التيار المار يساوي:', options: ['0.33 A', '3 A', '8 A', '48 A'], correctIndex: 1,
    explanation: 'I=V/R=12/4=3 A.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – التيار الكهربائي – المقاومة', tawjihiStyleYear: '2026', distractorDesign: 'ضرب V×R أو عكس القسمة',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-05', subject: 'الفيزياء', unit: 'الحركة الدورانية', lesson: 'الزخم الزاوي', skill: 'الزخم الزاوي', difficulty: 'صعب',
    text: 'عند انعدام محصلة العزوم الخارجية على نظام، فإن الكمية التي تبقى محفوظة هي:', options: ['الطاقة الحركية دائمًا', 'الزخم الزاوي', 'السرعة الزاوية دائمًا', 'عزم القصور دائمًا'], correctIndex: 1,
    explanation: 'غياب العزم الخارجي يؤدي إلى حفظ الزخم الزاوي، حتى لو تغير عزم القصور والسرعة الزاوية.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – الحركة الدورانية – الزخم الزاوي', tawjihiStyleYear: '2026', distractorDesign: 'تمييز الكمية المحفوظة عن عواملها',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-01', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات', lesson: 'تطبيقات على حفظ الزخم الخطي', skill: 'حفظ الزخم', difficulty: 'متوسط',
    text: 'متزلجان ساكنان يدفع أحدهما الآخر في اتجاهين متعاكسين. إذا كان النظام معزولًا، فإن مجموع زخميهما بعد الدفع:', options: ['موجب دائمًا', 'سالب دائمًا', 'يساوي صفرًا', 'يساوي مجموع كتلتيهما'], correctIndex: 2,
    explanation: 'الزخم الكلي الابتدائي صفر، فيبقى صفرًا عند غياب قوة خارجية محصلة.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – حفظ الزخم الخطي', tawjihiStyleYear: '2026', distractorDesign: 'الخلط بين الزخم والكتلة واتجاه الإشارة',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-02', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات', lesson: 'الزخم الخطي والدفع', skill: 'الدفع', difficulty: 'صعب',
    text: 'تزيد وسادة هوائية زمن توقف الراكب أثناء التصادم مع بقاء التغير في الزخم نفسه. الأثر الأساسي هو:', options: ['زيادة القوة المتوسطة', 'تقليل القوة المتوسطة', 'زيادة التغير في الزخم', 'جعل الزخم محفوظًا للراكب وحده'], correctIndex: 1,
    explanation: 'J=FΔt=Δp؛ عند ثبات Δp، زيادة زمن التأثير تقلل القوة المتوسطة.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – الدفع والزخم', tawjihiStyleYear: '2026', distractorDesign: 'تفسير فيزيائي واقعي للدفع',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-03', subject: 'الفيزياء', unit: 'الحركة الدورانية', lesson: 'العزم والاتزان السكوني', skill: 'اتزان سكوني', difficulty: 'متوسط',
    text: 'لإبقاء قضيب ساكنًا حول محور دوران، يجب أن يكون:', options: ['مجموع القوى فقط صفرًا', 'مجموع العزوم فقط صفرًا', 'مجموع القوى ومجموع العزوم كلاهما صفرًا', 'عزم القصور صفرًا'], correctIndex: 2,
    explanation: 'الاتزان السكوني يتطلب الاتزان الانتقالي والدوراني معًا.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – الاتزان السكوني', tawjihiStyleYear: '2026', distractorDesign: 'اختيار شرط واحد بدل الشرطين',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-04', subject: 'الفيزياء', unit: 'الحركة الدورانية', lesson: 'ديناميكا الحركة الدورانية', skill: 'ديناميكا دورانية', difficulty: 'متقدم',
    text: 'يؤثر العزم نفسه في قرصين، لكن عزم القصور للقرص A ضعف B. نسبة التسارع الزاوي αA/αB تساوي:', options: ['2', '1', '1/2', '1/4'], correctIndex: 2,
    explanation: 'τ=Iα؛ عند العزم نفسه تكون α عكسية مع I.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – ديناميكا الحركة الدورانية', tawjihiStyleYear: '2026', distractorDesign: 'علاقة عكسية بين I وα',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-05', subject: 'الفيزياء', unit: 'الكهرباء السكونية', lesson: 'المجال الكهربائي', skill: 'مجال شحنة نقطية', difficulty: 'متوسط',
    text: 'إذا تضاعفت المسافة عن شحنة نقطية، فإن مقدار المجال الكهربائي يصبح:', options: ['ضعفين', 'نصفًا', 'ربعًا', 'أربعة أضعاف'], correctIndex: 2,
    explanation: 'E∝1/r²، فتضاعف المسافة يجعل المجال ربع قيمته.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – المجال الكهربائي', tawjihiStyleYear: '2026', distractorDesign: 'الخلط بين التناسب العكسي والعكسي التربيعي',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-06', subject: 'الفيزياء', unit: 'الكهرباء السكونية', lesson: 'الجهد الكهربائي', skill: 'الجهد والطاقة', difficulty: 'صعب',
    text: 'شحنة موجبة تتحرك تلقائيًا في اتجاه المجال الكهربائي. طاقة وضعها الكهربائية عادةً:', options: ['تزداد', 'تقل', 'تبقى ثابتة حتمًا', 'تساوي صفرًا دائمًا'], correctIndex: 1,
    explanation: 'الشحنة الموجبة تتحرك من جهد أعلى إلى جهد أقل فتقل طاقة وضعها الكهربائية.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – الجهد الكهربائي', tawjihiStyleYear: '2026', distractorDesign: 'الخلط بين اتجاه المجال والجهد والطاقة',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-07', subject: 'الفيزياء', unit: 'التيار الكهربائي', lesson: 'الدارة البسيطة والقدرة الكهربائية', skill: 'قدرة كهربائية', difficulty: 'متوسط',
    text: 'جهاز يعمل عند 12 V ويمر فيه تيار 2 A. قدرته الكهربائية تساوي:', options: ['6 W', '14 W', '24 W', '144 W'], correctIndex: 2,
    explanation: 'P=VI=12×2=24 W.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – القدرة الكهربائية', tawjihiStyleYear: '2026', distractorDesign: 'قسمة أو جمع أو تربيع الجهد',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-08', subject: 'الفيزياء', unit: 'التيار الكهربائي', lesson: 'توصيل المقاومات وقاعدتا كيرشوف', skill: 'توصيل مقاومات', difficulty: 'متوسط',
    text: 'مقاومتان 3 Ω و6 Ω موصولتان على التوالي. المقاومة المكافئة تساوي:', options: ['2 Ω', '3 Ω', '9 Ω', '18 Ω'], correctIndex: 2,
    explanation: 'في التوالي تجمع المقاومات: Req=3+6=9 Ω.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – توصيل المقاومات', tawjihiStyleYear: '2026', distractorDesign: 'قانون التوازي أو حاصل الضرب',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-09', subject: 'الفيزياء', unit: 'التيار الكهربائي', lesson: 'توصيل المقاومات وقاعدتا كيرشوف', skill: 'كيرشوف', difficulty: 'صعب',
    text: 'عند نقطة تفرع في دارة، يدخل تيار 5 A ويتفرع إلى تيارين أحدهما 2 A. قيمة التيار الآخر:', options: ['2 A', '3 A', '5 A', '7 A'], correctIndex: 1,
    explanation: 'قاعدة كيرشوف للتيار: مجموع الداخل = مجموع الخارج، لذا 5=2+I.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – قاعدة كيرشوف للتيار', tawjihiStyleYear: '2026', distractorDesign: 'جمع التيارات بدل حفظ الشحنة',
  ),
  ExamQuestion(
    id: 'v11-ph-tr-10', subject: 'الفيزياء', unit: 'الحركة الدورانية', lesson: 'الزخم الزاوي', skill: 'حفظ الزخم الزاوي', difficulty: 'متوسط',
    text: 'متزلج يدور ثم يضم ذراعيه نحو جسمه مع إهمال العزم الخارجي. ماذا يحدث غالبًا؟', options: ['يقل عزم القصور وتزداد السرعة الزاوية', 'يزداد عزم القصور وتزداد السرعة الزاوية', 'تبقى السرعة الزاوية ثابتة', 'يصبح الزخم الزاوي صفرًا'], correctIndex: 0,
    explanation: 'L=Iω محفوظ؛ عندما يقل I تزداد ω.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'فيزياء 12 – حفظ الزخم الزاوي', tawjihiStyleYear: '2026', distractorDesign: 'العلاقة بين I وω عند حفظ L',
  ),

  // -------------------------------------------------------------------------
  // BIOLOGY — 5 BOOK-GROUNDED + 10 TRANSFER
  // -------------------------------------------------------------------------
  ExamQuestion(
    id: 'v11-bi-bk-01', subject: 'الأحياء', unit: 'كيمياء الحياة', lesson: 'المركبات العضوية الحيوية', skill: 'بناء الجزيئات الحيوية', difficulty: 'سهل',
    text: 'الوحدات البنائية الأساسية للبروتينات هي:', options: ['الأحماض الأمينية', 'الأحماض الدهنية', 'النيوكليوتيدات', 'السكريات الثنائية'], correctIndex: 0,
    explanation: 'البروتينات بوليمرات تتكون من أحماض أمينية مرتبطة بروابط ببتيدية.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'علوم حياتية 12 – كيمياء الحياة – المركبات العضوية الحيوية', tawjihiStyleYear: '2026', distractorDesign: 'وحدات بنائية لمركبات حيوية أخرى',
  ),
  ExamQuestion(
    id: 'v11-bi-bk-02', subject: 'الأحياء', unit: 'كيمياء الحياة', lesson: 'الإنزيمات وجزيء حفظ الطاقة ATP', skill: 'الإنزيمات', difficulty: 'متوسط',
    text: 'تعمل الإنزيمات غالبًا على تسريع التفاعلات من خلال:', options: ['رفع طاقة التنشيط', 'خفض طاقة التنشيط', 'زيادة درجة الحرارة داخل الخلية دائمًا', 'تغيير نواتج التفاعل النهائية'], correctIndex: 1,
    explanation: 'الإنزيم يوفر مسارًا أقل في طاقة التنشيط دون تغيير النواتج النهائية.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'علوم حياتية 12 – كيمياء الحياة – الإنزيمات', tawjihiStyleYear: '2026', distractorDesign: 'أثر الحفاز مقابل نتيجة التفاعل',
  ),
  ExamQuestion(
    id: 'v11-bi-bk-03', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات', lesson: 'دورة الخلية', skill: 'دورة الخلية', difficulty: 'متوسط',
    text: 'الطور الذي يتضاعف فيه DNA ضمن دورة الخلية هو:', options: ['G1', 'S', 'G2', 'M'], correctIndex: 1,
    explanation: 'يحدث تضاعف DNA في طور S من الطور البيني.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'علوم حياتية 12 – دورة الخلية – طور S', tawjihiStyleYear: '2026', distractorDesign: 'مراحل متجاورة من دورة الخلية',
  ),
  ExamQuestion(
    id: 'v11-bi-bk-04', subject: 'الأحياء', unit: 'الوراثة', lesson: 'وراثة الصفات المندلية', skill: 'الوراثة المندلية', difficulty: 'متوسط',
    text: 'إذا كان الفرد يحمل أليلين متماثلين للصفة نفسها، يوصف بأنه:', options: ['هجين', 'متماثل الأليلات', 'متعدد الجينات', 'مرتبط بالجنس'], correctIndex: 1,
    explanation: 'وجود أليلين متماثلين يعني أن النمط الجيني متماثل الأليلات.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'علوم حياتية 12 – الوراثة – الصفات المندلية', tawjihiStyleYear: '2026', distractorDesign: 'مصطلحات وراثية من الدرس نفسه',
  ),
  ExamQuestion(
    id: 'v11-bi-bk-05', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية', lesson: 'أدوات التكنولوجيا الحيوية', skill: 'تقنيات حيوية', difficulty: 'صعب',
    text: 'الأداة التي تُستخدم لقطع DNA عند تسلسلات محددة هي:', options: ['إنزيمات التقييد', 'الريبوسومات', 'ATP فقط', 'الأجسام المضادة'], correctIndex: 0,
    explanation: 'إنزيمات التقييد تتعرف إلى تسلسلات محددة وتقطع DNA عندها أو قربها.', sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'علوم حياتية 12 – التكنولوجيا الحيوية – أدواتها', tawjihiStyleYear: '2026', distractorDesign: 'أدوات خلوية وحيوية مختلفة الوظيفة',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-01', subject: 'الأحياء', unit: 'كيمياء الحياة', lesson: 'الإنزيمات وجزيء حفظ الطاقة ATP', skill: 'تفسير نشاط الإنزيم', difficulty: 'متوسط',
    text: 'في تجربة، ارتفع نشاط إنزيم تدريجيًا حتى 37°C ثم انخفض بشدة عند 70°C. التفسير الأفضل للانخفاض هو:', options: ['زيادة عدد الركائز', 'تغير البنية الفراغية للإنزيم', 'تحول ATP إلى DNA', 'زيادة عدد الجينات'], correctIndex: 1,
    explanation: 'درجات الحرارة العالية قد تسبب تغيرًا في البنية الفراغية للإنزيم فتقل فعاليته.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – الإنزيمات – العوامل المؤثرة', tawjihiStyleYear: '2026', distractorDesign: 'تفسير بيانات تجربة بدل تعريف مباشر',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-02', subject: 'الأحياء', unit: 'كيمياء الحياة', lesson: 'التفاعلات الكيميائية في الخلية', skill: 'ATP والطاقة', difficulty: 'متوسط',
    text: 'خلية عضلية تحتاج طاقة سريعة لانقباض متكرر. الجزيء الذي يمثل المصدر المباشر الأكثر شيوعًا للطاقة الخلوية هو:', options: ['ATP', 'DNA', 'الكولسترول', 'السليلوز'], correctIndex: 0,
    explanation: 'ATP هو عملة الطاقة المباشرة في الخلية.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – ATP والتفاعلات الخلوية', tawjihiStyleYear: '2026', distractorDesign: 'جزيئات حيوية حقيقية لكن بوظائف مختلفة',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-03', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات', lesson: 'دورة الخلية', skill: 'ضبط دورة الخلية', difficulty: 'صعب',
    text: 'إذا فشلت نقطة تفتيش خلوية في إيقاف خلية ذات DNA متضرر قبل الانقسام، فأي نتيجة تصبح أكثر احتمالًا؟', options: ['منع انتقال الطفرات للخلايا البنوية', 'تكاثر خلايا تحمل تلفًا وراثيًا', 'توقف تصنيع البروتين كليًا دائمًا', 'تحول DNA إلى RNA'], correctIndex: 1,
    explanation: 'فشل نقاط التفتيش يسمح باستمرار الانقسام رغم وجود تلف، ما يزيد احتمال انتقال الطفرات.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – دورة الخلية – ضبط الانقسام', tawjihiStyleYear: '2026', distractorDesign: 'سبب ونتيجة في سياق خلوي جديد',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-04', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات', lesson: 'تضاعف DNA والتعبير الجيني', skill: 'التعبير الجيني', difficulty: 'متوسط',
    text: 'إذا تغير تسلسل قواعد جين فأصبح mRNA الناتج مختلفًا، فإن أول مستوى قد يتأثر مباشرة هو:', options: ['تسلسل الكودونات', 'عدد الكروموسومات دائمًا', 'غشاء الخلية فقط', 'كمية الماء في الخلية فقط'], correctIndex: 0,
    explanation: 'تغير تسلسل DNA قد يغير تسلسل mRNA والكودونات، ما قد يؤثر في البروتين.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – التعبير الجيني', tawjihiStyleYear: '2026', distractorDesign: 'تتبّع أثر التغير عبر مستويات التعبير الجيني',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-05', subject: 'الأحياء', unit: 'الوراثة', lesson: 'وراثة الصفات المندلية', skill: 'مربع بانيت', difficulty: 'متوسط',
    text: 'في تزاوج Aa × Aa لصفة سيادة تامة، احتمال النمط الجيني aa يساوي:', options: ['0%', '25%', '50%', '75%'], correctIndex: 1,
    explanation: 'النسب الجينية المتوقعة 1AA:2Aa:1aa، أي 25% لـ aa.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – الوراثة المندلية', tawjihiStyleYear: '2026', distractorDesign: 'الخلط بين النسبة الجينية والمظهرية',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-06', subject: 'الأحياء', unit: 'الوراثة', lesson: 'الوراثة بعد مندل', skill: 'أنماط وراثة', difficulty: 'متقدم',
    text: 'إذا ظهر في الفرد غير المتماثل للأليلات نمط ظاهري وسيط بين الأبوين، فإن النمط الوراثي الأقرب هو:', options: ['السيادة التامة', 'السيادة غير التامة', 'صفة مرتبطة بالجنس حتمًا', 'طفرة صامتة'], correctIndex: 1,
    explanation: 'السيادة غير التامة تعطي غالبًا مظهرًا وسيطًا في الفرد غير المتماثل.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – الوراثة بعد مندل', tawjihiStyleYear: '2026', distractorDesign: 'تمييز نمط وراثة من وصف ظاهري',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-07', subject: 'الأحياء', unit: 'الوراثة', lesson: 'الطفرات والاختلالات الوراثية', skill: 'تحليل طفرة', difficulty: 'صعب',
    text: 'طفرة استبدال قاعدة واحدة لم تغيّر الحمض الأميني الناتج. توصف غالبًا بأنها:', options: ['طفرة صامتة', 'حذف كروموسوم كامل', 'انقلاب كروموسومي', 'تضاعف جين كامل دائمًا'], correctIndex: 0,
    explanation: 'قد يؤدي ترادف الشفرة الجينية إلى بقاء الحمض الأميني نفسه رغم تغير الكودون.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – الطفرات', tawjihiStyleYear: '2026', distractorDesign: 'تمييز مستوى الطفرة من أثرها',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-08', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية', lesson: 'أدوات التكنولوجيا الحيوية', skill: 'DNA معاد التركيب', difficulty: 'متوسط',
    text: 'لإدخال جين بشري في بكتيريا لإنتاج بروتين، يحتاج الباحث عادةً إلى ناقل مناسب مثل:', options: ['البلازميد', 'الريبوسوم كناقل DNA', 'الغشاء الخلوي وحده', 'جزيء ATP كناقل وراثي'], correctIndex: 0,
    explanation: 'البلازميدات تستخدم كثيرًا كنواقل لإدخال DNA إلى البكتيريا.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – أدوات التكنولوجيا الحيوية', tawjihiStyleYear: '2026', distractorDesign: 'مكونات خلوية حقيقية لكن ليست نواقل جينية',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-09', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية', lesson: 'تطبيقات التكنولوجيا الحيوية', skill: 'تطبيقات حيوية', difficulty: 'متوسط',
    text: 'إنتاج الإنسولين البشري باستخدام بكتيريا معدلة وراثيًا يمثل تطبيقًا لـ:', options: ['DNA معاد التركيب', 'الانتخاب الطبيعي فقط', 'الانقسام المنصف فقط', 'التنفس الخلوي فقط'], correctIndex: 0,
    explanation: 'يُدخل الجين البشري المناسب في كائن مضيف لإنتاج البروتين المطلوب.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – تطبيقات التكنولوجيا الحيوية', tawjihiStyleYear: '2026', distractorDesign: 'اختيار التقنية التي تفسر التطبيق',
  ),
  ExamQuestion(
    id: 'v11-bi-tr-10', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات', lesson: 'الانقسام الخلوي وأهميته', skill: 'الانقسام الخلوي', difficulty: 'سهل',
    text: 'في نمو نسيج جلدي بعد جرح، نوع الانقسام المسؤول أساسًا عن زيادة عدد الخلايا الجسدية هو:', options: ['الانقسام المتساوي', 'الانقسام المنصف', 'الإخصاب', 'النسخ'], correctIndex: 0,
    explanation: 'الانقسام المتساوي ينتج خلايا جسدية جديدة للنمو والتعويض.', sourceLabel: 'نقل وفهم – مبني على مهارة من الكتاب الرسمي', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'transfer', sourceReference: 'علوم حياتية 12 – الانقسام الخلوي وأهميته', tawjihiStyleYear: '2026', distractorDesign: 'ربط العملية الحيوية بموقف حياتي',
  ),

  // -------------------------------------------------------------------------
  // V11 difficulty-balancing book-grounded items (12)
  // -------------------------------------------------------------------------
  ExamQuestion(
    id: 'v11-en-bk-01', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Reading: language and the world', skill: 'استنتاج من النص', difficulty: 'صعب',
    text: 'A writer presents two studies that reach different conclusions, then points out that their methods were not identical. What is the writer mainly doing?',
    options: ['Rejecting all research', 'Qualifying a comparison between the studies', 'Changing the topic completely', 'Proving both studies are identical'],
    correctIndex: 1,
    explanation: 'Pointing out methodological differences qualifies how directly the findings can be compared.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'High Note 12 S1 – Unit 1 – Reading strategies and linguistic relativity', tawjihiStyleYear: '2026',
    distractorDesign: 'خيارات تفسيرية متقاربة تتطلب فهم وظيفة الجملة في النص',
  ),
  ExamQuestion(
    id: 'v11-en-bk-02', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'Writing: a for-and-against essay', skill: 'paraphrasing', difficulty: 'صعب',
    text: 'Which sentence best paraphrases: “Advertising can influence decisions without consumers being fully aware of it”?',
    options: ['Consumers always know exactly why they buy things.', 'Advertising may shape choices even when people do not consciously notice the influence.', 'Advertising has no effect on consumer behaviour.', 'Consumers only make decisions after studying advertisements.'],
    correctIndex: 1,
    explanation: 'The second option preserves both ideas: influence on choices and limited conscious awareness.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'High Note 12 S1 – Unit 3 – Active Writing: Paraphrasing', tawjihiStyleYear: '2026',
    distractorDesign: 'تغيير درجة التعميم أو عكس المعنى',
  ),
  ExamQuestion(
    id: 'v11-ma-bk-06', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية', lesson: 'نظريتا الباقي والعوامل',
    skill: 'نظرية العوامل', difficulty: 'سهل',
    text: 'إذا كان P(−1)=0، فإن أي مما يأتي عامل في P(x)؟',
    options: ['x−1', 'x+1', 'x', 'x+2'], correctIndex: 1,
    explanation: 'إذا كان P(a)=0 فإن (x−a) عامل؛ وعند a=−1 يكون العامل x+1.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'رياضيات 12 – نظريتا الباقي والعوامل', tawjihiStyleYear: '2026', distractorDesign: 'خطأ الإشارة في تحويل الجذر إلى عامل',
  ),
  ExamQuestion(
    id: 'v11-ch-bk-01', subject: 'الكيمياء', unit: 'حالات المادة', lesson: 'الحالة الغازية', skill: 'قوانين الغازات', difficulty: 'سهل',
    text: 'عند ثبوت الضغط، يزداد حجم كمية محددة من الغاز بزيادة درجة حرارتها المطلقة. هذه العلاقة تمثل قانون:',
    options: ['بويل', 'شارل', 'دالتون', 'هنري'], correctIndex: 1,
    explanation: 'قانون شارل يربط الحجم بدرجة الحرارة المطلقة عند ثبوت الضغط.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'كيمياء 12 – حالات المادة – الحالة الغازية', tawjihiStyleYear: '2026', distractorDesign: 'قوانين من الوحدة ومفاهيم قريبة',
  ),
  ExamQuestion(
    id: 'v11-ch-bk-02', subject: 'الكيمياء', unit: 'المحاليل', lesson: 'تصنيف المحاليل', skill: 'تصنيف المحاليل', difficulty: 'سهل',
    text: 'في محلول السكر في الماء، يُعد الماء عادةً:',
    options: ['المذاب', 'المذيب', 'الراسب', 'المحفز'], correctIndex: 1,
    explanation: 'الماء هو الوسط الذي يذوب فيه السكر، لذلك هو المذيب.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'كيمياء 12 – المحاليل – تصنيف المحاليل', tawjihiStyleYear: '2026', distractorDesign: 'تمييز أدوار مكونات المحلول',
  ),
  ExamQuestion(
    id: 'v11-ch-bk-03', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها', lesson: 'الحموض والقواعد', skill: 'مفهوم برونستد-لوري', difficulty: 'سهل',
    text: 'وفق برونستد-لوري، القاعدة هي مادة:',
    options: ['تمنح بروتونًا', 'تستقبل بروتونًا', 'تمنح نيوترونًا', 'لا تشارك في انتقال البروتون'], correctIndex: 1,
    explanation: 'قاعدة برونستد-لوري تستقبل بروتون H+.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'كيمياء 12 – الحموض والقواعد', tawjihiStyleYear: '2026', distractorDesign: 'عكس تعريف الحمض والقاعدة',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-06', subject: 'الفيزياء', unit: 'الكهرباء السكونية', lesson: 'الجهد الكهربائي', skill: 'الجهد الكهربائي', difficulty: 'سهل',
    text: 'وحدة قياس فرق الجهد الكهربائي في النظام الدولي هي:',
    options: ['الأمبير', 'الفولت', 'الأوم', 'الكولوم'], correctIndex: 1,
    explanation: 'فرق الجهد يقاس بالفولت.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – الكهرباء السكونية – الجهد الكهربائي', tawjihiStyleYear: '2026', distractorDesign: 'وحدات كهربائية من المجال نفسه',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-07', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات', lesson: 'الزخم الخطي والدفع', skill: 'الزخم الخطي', difficulty: 'سهل',
    text: 'إذا كان جسم ساكنًا بالنسبة لمرجع معين، فإن زخمه الخطي بالنسبة لذلك المرجع يساوي:',
    options: ['صفرًا', 'كتلته', 'تسارعه', 'طاقة وضعه'], correctIndex: 0,
    explanation: 'p=mv، وعند v=0 يكون الزخم صفرًا.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – الزخم الخطي والدفع', tawjihiStyleYear: '2026', distractorDesign: 'خلط الزخم بكمية فيزيائية أخرى',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-08', subject: 'الفيزياء', unit: 'التيار الكهربائي', lesson: 'توصيل المقاومات وقاعدتا كيرشوف', skill: 'قاعدة كيرشوف للجهد', difficulty: 'صعب',
    text: 'في حلقة مغلقة لدارة كهربائية، تنص قاعدة كيرشوف للجهد على أن:',
    options: ['مجموع التيارات الداخلة يساوي صفرًا', 'المجموع الجبري لتغيرات الجهد حول الحلقة يساوي صفرًا', 'كل المقاومات متساوية', 'القدرة الكهربائية محفوظة في كل عنصر منفرد'],
    correctIndex: 1,
    explanation: 'قاعدة الحلقة تعتمد على حفظ الطاقة: المجموع الجبري لفروق وارتفاعات الجهد حول مسار مغلق يساوي صفرًا.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – قاعدتا كيرشوف', tawjihiStyleYear: '2026', distractorDesign: 'الخلط بين قاعدة العقدة وقاعدة الحلقة',
  ),
  ExamQuestion(
    id: 'v11-ph-bk-09', subject: 'الفيزياء', unit: 'الحركة الدورانية', lesson: 'ديناميكا الحركة الدورانية', skill: 'عزم القصور', difficulty: 'صعب',
    text: 'لجسمين لهما الكتلة نفسها، يكون عزم القصور حول محور أكبر عادةً عندما:',
    options: ['تتركز الكتلة أقرب إلى المحور', 'تتوزع الكتلة أبعد عن المحور', 'تكون السرعة الخطية صفرًا', 'تكون محصلة القوى صفرًا فقط'],
    correctIndex: 1,
    explanation: 'عزم القصور يعتمد على توزيع الكتلة بالنسبة لمحور الدوران ويزداد بابتعاد الكتلة عنه.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'فيزياء 12 – ديناميكا الحركة الدورانية – عزم القصور', tawjihiStyleYear: '2026', distractorDesign: 'تمييز أثر توزيع الكتلة عن السرعة والقوة',
  ),
  ExamQuestion(
    id: 'v11-bi-bk-06', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات', lesson: 'تضاعف DNA والتعبير الجيني', skill: 'تصنيع البروتين', difficulty: 'صعب',
    text: 'أي تسلسل يمثل انتقال المعلومات الوراثية في التعبير الجيني بصورة عامة؟',
    options: ['Protein → RNA → DNA', 'DNA → RNA → Protein', 'RNA → DNA → ATP', 'ATP → DNA → Protein'], correctIndex: 1,
    explanation: 'في التعبير الجيني المعتاد تُنسخ المعلومات من DNA إلى RNA ثم تُترجم إلى بروتين.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'علوم حياتية 12 – تضاعف DNA والتعبير الجيني', tawjihiStyleYear: '2026', distractorDesign: 'تبديل اتجاه تدفق المعلومات',
  ),
  ExamQuestion(
    id: 'v11-bi-bk-07', subject: 'الأحياء', unit: 'الوراثة', lesson: 'الطفرات والاختلالات الوراثية', skill: 'الطفرات', difficulty: 'صعب',
    text: 'أي تغير مما يأتي يحدث على مستوى الجين لا على مستوى عدد الكروموسومات؟',
    options: ['استبدال قاعدة نيتروجينية في تسلسل DNA', 'التثلث الصبغي', 'فقد كروموسوم كامل', 'زيادة مجموعة كروموسومية كاملة'], correctIndex: 0,
    explanation: 'استبدال قاعدة مثال على طفرة جينية، بينما الخيارات الأخرى تغيرات كروموسومية عددية.',
    sourceLabel: 'من الكتاب الرسمي – صياغة تدريبية', curriculumYear: '2026-2027', verifiedFromOfficialCurriculum: true,
    questionOrigin: 'officialBook', sourceReference: 'علوم حياتية 12 – الطفرات والاختلالات الوراثية', tawjihiStyleYear: '2026', distractorDesign: 'تمييز مستوى الطفرة الجينية من الكروموسومية',
  ),
];
