import 'models.dart';
import 'curriculum_data.dart';
import 'v7_questions.dart';

/// إضافات V6.
/// الكتب الثلاثة مدرجة رسميًا لدى المركز الوطني للعام 2026-2027.
/// عناوين الوحدات والدروس هنا فُهرست بمطابقة فهارس الخطة الجديدة المتاحة حاليًا.
/// الأسئلة تدريبية أصلية وليست مقتبسة حرفيًا من الكتاب أو أسئلة وزارية.

const v6CurriculumUnits = <CurriculumUnit>[
  // الرياضيات
  CurriculumUnit(
    subject: 'الرياضيات',
    number: 1,
    title: 'الاقترانات والمقادير الجبرية',
    sourceId: 'nccd-g12-math-s1-2026',
    lessons: ['نظريتا الباقي والعوامل', 'الكسور الجزئية'],
  ),
  CurriculumUnit(
    subject: 'الرياضيات',
    number: 2,
    title: 'المتطابقات والمعادلات المثلثية',
    sourceId: 'nccd-g12-math-s1-2026',
    lessons: ['المتطابقات المثلثية', 'حل المعادلات المثلثية'],
  ),
  CurriculumUnit(
    subject: 'الرياضيات',
    number: 3,
    title: 'التفاضل وتطبيقاته',
    sourceId: 'nccd-g12-math-s1-2026',
    lessons: ['قواعد الاشتقاق', 'قاعدة السلسلة', 'الاشتقاق الضمني', 'تطبيقات المشتقة'],
  ),
  CurriculumUnit(
    subject: 'الرياضيات',
    number: 4,
    title: 'الأعداد المركبة',
    sourceId: 'nccd-g12-math-s1-2026',
    lessons: ['الأعداد المركبة', 'العمليات على الأعداد المركبة'],
  ),

  // الفيزياء
  CurriculumUnit(
    subject: 'الفيزياء',
    number: 1,
    title: 'الزخم الخطي والتصادمات',
    sourceId: 'nccd-g12-physics-s1-2026',
    lessons: ['الزخم الخطي والدفع', 'تطبيقات على حفظ الزخم الخطي'],
  ),
  CurriculumUnit(
    subject: 'الفيزياء',
    number: 2,
    title: 'الحركة الدورانية',
    sourceId: 'nccd-g12-physics-s1-2026',
    lessons: ['العزم والاتزان السكوني', 'ديناميكا الحركة الدورانية', 'الزخم الزاوي'],
  ),
  CurriculumUnit(
    subject: 'الفيزياء',
    number: 3,
    title: 'الكهرباء السكونية',
    sourceId: 'nccd-g12-physics-s1-2026',
    lessons: ['المجال الكهربائي', 'الجهد الكهربائي'],
  ),
  CurriculumUnit(
    subject: 'الفيزياء',
    number: 4,
    title: 'التيار الكهربائي',
    sourceId: 'nccd-g12-physics-s1-2026',
    lessons: ['المقاومة والقوة الدافعة الكهربائية', 'الدارة البسيطة والقدرة الكهربائية', 'توصيل المقاومات وقاعدتا كيرشوف'],
  ),

  // العلوم الحياتية
  CurriculumUnit(
    subject: 'الأحياء',
    number: 1,
    title: 'كيمياء الحياة',
    sourceId: 'nccd-g12-bio-s1-2026',
    lessons: ['المركبات العضوية الحيوية', 'الإنزيمات وجزيء حفظ الطاقة ATP', 'التفاعلات الكيميائية في الخلية'],
  ),
  CurriculumUnit(
    subject: 'الأحياء',
    number: 2,
    title: 'دورة الخلية وتصنيع البروتينات',
    sourceId: 'nccd-g12-bio-s1-2026',
    lessons: ['دورة الخلية', 'الانقسام الخلوي وأهميته', 'تضاعف DNA والتعبير الجيني'],
  ),
  CurriculumUnit(
    subject: 'الأحياء',
    number: 3,
    title: 'الوراثة',
    sourceId: 'nccd-g12-bio-s1-2026',
    lessons: ['وراثة الصفات المندلية', 'الوراثة بعد مندل', 'الطفرات والاختلالات الوراثية'],
  ),
  CurriculumUnit(
    subject: 'الأحياء',
    number: 4,
    title: 'التكنولوجيا الحيوية',
    sourceId: 'nccd-g12-bio-s1-2026',
    lessons: ['أدوات التكنولوجيا الحيوية', 'تطبيقات التكنولوجيا الحيوية'],
  ),
];

const v6CurriculumQuestions = <ExamQuestion>[
  // ========================= الرياضيات =========================
  ExamQuestion(
    id: 'v6-math-u1-01', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'نظريتا الباقي والعوامل', difficulty: 'متوسط', skill: 'تطبيق',
    text: 'إذا كان p(x)=x³−4x+1، فما باقي قسمة p(x) على (x−2)؟',
    options: ['0', '1', '2', '5'], correctIndex: 1,
    explanation: 'بحسب نظرية الباقي يكون الباقي p(2)=8−8+1=1.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u1-02', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'نظريتا الباقي والعوامل', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'إذا كان p(−3)=0، فأي العوامل الآتية عامل في p(x)؟',
    options: ['x−3', 'x+3', 'x−1', 'x+1'], correctIndex: 1,
    explanation: 'إذا كان p(a)=0 فإن (x−a) عامل؛ وعند a=−3 يكون العامل (x+3).',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u1-03', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'الكسور الجزئية', difficulty: 'متوسط', skill: 'تمثيل جبري',
    text: 'أي صورة هي الأنسب لتجزئة كسر مقامه (x−1)(x+2) إلى كسور جزئية؟',
    options: ['A/(x−1)+B/(x+2)', 'A/(x−1)² فقط', 'A/(x²+1)', 'A+B فقط'], correctIndex: 0,
    explanation: 'لكل عامل خطي مختلف في المقام كسر جزئي ببسط ثابت.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u1-04', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'الكسور الجزئية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'حتى يكون المقدار النسبي جاهزًا مباشرة للتجزئة إلى كسور جزئية، يجب أن تكون درجة البسط:',
    options: ['أكبر من درجة المقام', 'أقل من درجة المقام', 'مساوية دائمًا لدرجة المقام', 'صفرًا دائمًا'], correctIndex: 1,
    explanation: 'إذا لم تكن درجة البسط أقل من درجة المقام تُجرى القسمة أولًا.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u1-05', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'نظريتا الباقي والعوامل', difficulty: 'متوسط', skill: 'تطبيق',
    text: 'ما باقي قسمة x²+1 على x−1؟',
    options: ['0', '1', '2', '−2'], correctIndex: 2,
    explanation: 'الباقي يساوي p(1)=1²+1=2.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-math-u2-01', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'المتطابقات المثلثية', difficulty: 'سهل', skill: 'استدعاء',
    text: 'أي متطابقة مما يأتي صحيحة لجميع الزوايا التي تكون فيها الحدود معرفة؟',
    options: ['sin²x+cos²x=1', 'sin x+cos x=1', 'tan x=sin x·cos x', 'cos²x−sin²x=1 دائمًا'], correctIndex: 0,
    explanation: 'المتطابقة الأساسية هي sin²x+cos²x=1.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u2-02', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'المتطابقات المثلثية', difficulty: 'متوسط', skill: 'استدعاء',
    text: 'أي علاقة مكافئة للمتطابقة 1+tan²x ؟',
    options: ['csc²x', 'sec²x', 'sin²x', 'cos²x'], correctIndex: 1,
    explanation: '1+tan²x=sec²x.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u2-03', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'حل المعادلات المثلثية', difficulty: 'متوسط', skill: 'حل معادلات',
    text: 'ما حلول sin x=0 في الفترة [0,2π)؟',
    options: ['0 فقط', 'π فقط', '0 وπ', 'π/2 و3π/2'], correctIndex: 2,
    explanation: 'الجيب يساوي صفرًا عند مضاعفات π؛ وفي الفترة المطلوبة الحلّان 0 وπ.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u2-04', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'المتطابقات المثلثية', difficulty: 'متوسط', skill: 'تحويل',
    text: 'أي تعبير يساوي cos(2x)؟',
    options: ['2cos²x−1', '2sin x cos x', '1+2sin²x', 'sin²x+cos²x'], correctIndex: 0,
    explanation: 'من متطابقات ضعف الزاوية: cos(2x)=2cos²x−1.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u2-05', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'حل المعادلات المثلثية', difficulty: 'سهل', skill: 'تطبيق',
    text: 'إذا كانت θ زاوية حادة وtan θ=1، فما قياس θ؟',
    options: ['30°', '45°', '60°', '90°'], correctIndex: 1,
    explanation: 'tan 45°=1.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-math-u3-01', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'قواعد الاشتقاق', difficulty: 'سهل', skill: 'اشتقاق',
    text: 'إذا كان f(x)=x³−5x، فإن f′(x) تساوي:',
    options: ['3x²−5', 'x²−5', '3x−5', '3x²'], correctIndex: 0,
    explanation: 'مشتقة x³ هي 3x² ومشتقة −5x هي −5.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u3-02', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'قاعدة السلسلة', difficulty: 'متوسط', skill: 'اشتقاق',
    text: 'مشتقة (2x+1)⁴ هي:',
    options: ['4(2x+1)³', '8(2x+1)³', '8(2x+1)⁴', '2(2x+1)³'], correctIndex: 1,
    explanation: 'باستعمال قاعدة السلسلة: 4(2x+1)³×2=8(2x+1)³.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u3-03', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'الاشتقاق الضمني', difficulty: 'متوسط', skill: 'اشتقاق ضمني',
    text: 'إذا كانت x²+y²=25، فإن dy/dx يساوي:',
    options: ['x/y', '−x/y', '−y/x', '2x+2y'], correctIndex: 1,
    explanation: 'باشتقاق الطرفين: 2x+2y(dy/dx)=0، إذن dy/dx=−x/y.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u3-04', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'تطبيقات المشتقة', difficulty: 'متوسط', skill: 'تحليل',
    text: 'إذا كانت f′(x)>0 على فترة ما، فإن f(x) على تلك الفترة تكون:',
    options: ['متناقصة', 'متزايدة', 'ثابتة دائمًا', 'غير قابلة للاشتقاق'], correctIndex: 1,
    explanation: 'إشارة المشتقة الموجبة تدل على أن الاقتران متزايد.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u3-05', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'تطبيقات المشتقة', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'تُعد القيمة x=c قيمة حرجة لاقتران عندما:',
    options: ['f(c)=0 فقط', 'f′(c)=0 أو تكون المشتقة غير موجودة مع وجود f(c)', 'f′(c)=1 فقط', 'f(c)>0 دائمًا'], correctIndex: 1,
    explanation: 'القيم الحرجة ترتبط بانعدام المشتقة أو عدم وجودها عند نقطة ضمن مجال الاقتران.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-math-u4-01', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'الأعداد المركبة', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'قيمة i² تساوي:',
    options: ['1', '−1', 'i', '−i'], correctIndex: 1,
    explanation: 'تعرف الوحدة التخيلية بحيث i²=−1.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u4-02', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'العمليات على الأعداد المركبة', difficulty: 'سهل', skill: 'حساب',
    text: 'ناتج (3+2i)+(1−5i) هو:',
    options: ['4+7i', '2−3i', '4−3i', '3−5i'], correctIndex: 2,
    explanation: 'نجمع الجزأين الحقيقيين والمتخيلين كلًا على حدة: 4−3i.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u4-03', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'الأعداد المركبة', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'مرافق العدد 4−3i هو:',
    options: ['−4+3i', '4+3i', '−4−3i', '3+4i'], correctIndex: 1,
    explanation: 'المرافق يغير إشارة الجزء التخيلي فقط.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u4-04', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'الأعداد المركبة', difficulty: 'متوسط', skill: 'حساب',
    text: 'مقياس العدد المركب 3+4i يساوي:',
    options: ['3', '4', '5', '7'], correctIndex: 2,
    explanation: '|3+4i|=√(3²+4²)=5.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-math-u4-05', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'العمليات على الأعداد المركبة', difficulty: 'متوسط', skill: 'حساب',
    text: 'ما قيمة i²³؟',
    options: ['1', '−1', 'i', '−i'], correctIndex: 3,
    explanation: 'قوى i تتكرر كل 4؛ 23 باقي قسمته على 4 يساوي 3، إذن i²³=i³=−i.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  // ========================= الفيزياء =========================
  ExamQuestion(
    id: 'v6-phy-u1-01', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'الزخم الخطي والدفع', difficulty: 'سهل', skill: 'حساب',
    text: 'جسم كتلته 2 kg يتحرك بسرعة 3 m/s. مقدار زخمه الخطي يساوي:',
    options: ['1.5 kg·m/s', '5 kg·m/s', '6 kg·m/s', '9 kg·m/s'], correctIndex: 2,
    explanation: 'p=mv=2×3=6 kg·m/s.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u1-02', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'الزخم الخطي والدفع', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'الدفع المؤثر في جسم يساوي:',
    options: ['التغير في زخمه الخطي', 'زخمه النهائي فقط', 'كتلته مقسومة على الزمن', 'طاقته الحركية'], correctIndex: 0,
    explanation: 'مبرهنة الزخم–الدفع تنص على أن الدفع يساوي التغير في الزخم.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u1-03', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'تطبيقات على حفظ الزخم الخطي', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'في نظام معزول أثناء تصادم جسمين، أي كمية تكون محفوظة دائمًا؟',
    options: ['الزخم الخطي الكلي', 'الطاقة الحركية دائمًا', 'سرعة كل جسم', 'كتلة كل جسم مضروبة في تسارعه'], correctIndex: 0,
    explanation: 'الزخم الخطي الكلي محفوظ في النظام المعزول.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u1-04', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'تطبيقات على حفظ الزخم الخطي', difficulty: 'سهل', skill: 'تصنيف',
    text: 'إذا التصق جسمان معًا بعد التصادم، فإن التصادم يوصف بأنه:',
    options: ['مرن', 'عديم المرونة', 'دوراني', 'ساكن'], correctIndex: 1,
    explanation: 'عندما يلتصق الجسمان ويتحركان معًا بعد التصادم يكون التصادم عديم المرونة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u1-05', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'تطبيقات على حفظ الزخم الخطي', difficulty: 'متوسط', skill: 'مقارنة',
    text: 'في التصادم المرن لنظام معزول تكون الكميتان المحفوظتان:',
    options: ['الزخم الخطي والطاقة الحركية', 'السرعة والتسارع', 'القوة والطاقة الوضعية فقط', 'الحجم والكثافة'], correctIndex: 0,
    explanation: 'في التصادم المرن يحفظ كل من الزخم الخطي والطاقة الحركية.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-phy-u2-01', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'العزم والاتزان السكوني', difficulty: 'متوسط', skill: 'حساب',
    text: 'قوة مقدارها 10 N تؤثر عموديًا على ذراع طوله 0.5 m. مقدار العزم يساوي:',
    options: ['2 N·m', '5 N·m', '10 N·m', '20 N·m'], correctIndex: 1,
    explanation: 'عند التعامد τ=rF=0.5×10=5 N·m.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u2-02', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'العزم والاتزان السكوني', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'حتى يكون جسم صلب في اتزان سكوني يجب أن:',
    options: ['تساوي محصلة القوى صفرًا فقط', 'تساوي محصلة العزوم صفرًا فقط', 'تساوي محصلة القوى ومحصلة العزوم صفرًا', 'تكون سرعته الزاوية كبيرة'], correctIndex: 2,
    explanation: 'الاتزان السكوني يتطلب الاتزان الانتقالي والدوراني معًا.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u2-03', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'ديناميكا الحركة الدورانية', difficulty: 'متوسط', skill: 'علاقات',
    text: 'الطاقة الحركية الدورانية لجسم يدور حول محور ثابت تعطى بالعلاقة:',
    options: ['½Iω²', 'I/ω', 'mgh', 'FΔt'], correctIndex: 0,
    explanation: 'الطاقة الحركية الدورانية KER=½Iω².',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u2-04', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'الزخم الزاوي', difficulty: 'سهل', skill: 'علاقات',
    text: 'لجسم يدور حول محور ثابت، مقدار الزخم الزاوي يساوي:',
    options: ['Iω', 'I/ω', 'm/v', 'F/r'], correctIndex: 0,
    explanation: 'L=Iω.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u2-05', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'الزخم الزاوي', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'يحفظ الزخم الزاوي لنظام عندما يكون العزم الخارجي المحصل:',
    options: ['صفرًا', 'أكبر ما يمكن', 'مساويًا للكتلة', 'ثابتًا وغير صفري دائمًا'], correctIndex: 0,
    explanation: 'إذا كان العزم الخارجي المحصل صفرًا يبقى الزخم الزاوي الكلي ثابتًا.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-phy-u3-01', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'المجال الكهربائي', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'يعرف مقدار المجال الكهربائي عند نقطة بأنه:',
    options: ['القوة الكهربائية لكل وحدة شحنة اختبار موجبة', 'الشحنة لكل وحدة زمن', 'الطاقة لكل وحدة كتلة', 'المقاومة لكل وحدة طول'], correctIndex: 0,
    explanation: 'E=F/q لشحنة اختبار موجبة صغيرة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u3-02', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'المجال الكهربائي', difficulty: 'سهل', skill: 'تمثيل',
    text: 'اتجاه خطوط المجال الكهربائي حول شحنتين مختلفتي النوع يكون بصورة عامة:',
    options: ['من السالبة إلى الموجبة', 'من الموجبة إلى السالبة', 'دائريًا دائمًا', 'لا اتجاه لها'], correctIndex: 1,
    explanation: 'يُعرّف اتجاه المجال باتجاه القوة على شحنة اختبار موجبة؛ فتخرج الخطوط من الموجب وتتجه إلى السالب.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u3-03', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'المجال الكهربائي', difficulty: 'متوسط', skill: 'تطبيق',
    text: 'للسطح المستوي في مجال منتظم، يكون التدفق الكهربائي EAcosθ أعظم ما يمكن عندما θ تساوي:',
    options: ['0°', '45°', '90°', '180° فقط'], correctIndex: 0,
    explanation: 'القيمة العظمى الموجبة تحصل عندما cosθ=1 أي θ=0°.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u3-04', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'الجهد الكهربائي', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'عند التحرك في اتجاه خطوط مجال كهربائي منتظم، فإن الجهد الكهربائي:',
    options: ['يزداد', 'يتناقص', 'يبقى ثابتًا دائمًا', 'يتحول إلى تيار'], correctIndex: 1,
    explanation: 'يتناقص الجهد في اتجاه المجال الكهربائي.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u3-05', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'المجال الكهربائي', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'في الاتزان الكهروستاتيكي يكون المجال الكهربائي داخل مادة موصلة:',
    options: ['صفراً', 'ثابتاً وغير صفري', 'لانهائياً', 'مساوياً للجهد'], correctIndex: 0,
    explanation: 'داخل الموصل المتزن كهروستاتيكيًا يكون المجال الكهربائي صفراً.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-phy-u4-01', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'المقاومة والقوة الدافعة الكهربائية', difficulty: 'سهل', skill: 'حساب',
    text: 'إذا عبرت شحنة مقدارها 6 C مقطع موصل خلال 2 s، فالتيار يساوي:',
    options: ['2 A', '3 A', '6 A', '12 A'], correctIndex: 1,
    explanation: 'I=ΔQ/Δt=6/2=3 A.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u4-02', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'المقاومة والقوة الدافعة الكهربائية', difficulty: 'متوسط', skill: 'حساب',
    text: 'يمر تيار 2 A في مقاومة 5 Ω. فرق الجهد عليها يساوي:',
    options: ['2.5 V', '7 V', '10 V', '25 V'], correctIndex: 2,
    explanation: 'من قانون أوم V=IR=2×5=10 V.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u4-03', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'الدارة البسيطة والقدرة الكهربائية', difficulty: 'متوسط', skill: 'حساب',
    text: 'جهاز يعمل عند فرق جهد 12 V ويسحب تيارًا 2 A. قدرته الكهربائية:',
    options: ['6 W', '10 W', '14 W', '24 W'], correctIndex: 3,
    explanation: 'P=VI=12×2=24 W.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u4-04', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'توصيل المقاومات وقاعدتا كيرشوف', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'عند توصيل مقاومتين على التوالي، فإن المقاومة المكافئة:',
    options: ['تساوي مجموع المقاومتين', 'أقل من أصغر مقاومة دائمًا', 'تساوي حاصل ضربهما فقط', 'تساوي صفراً'], correctIndex: 0,
    explanation: 'في التوالي Req=R1+R2+…',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-phy-u4-05', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'توصيل المقاومات وقاعدتا كيرشوف', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'تنص قاعدة كيرشوف للنقاط على أن:',
    options: ['مجموع التيارات الداخلة إلى نقطة يساوي مجموع الخارجة منها', 'الجهد يساوي صفراً في كل مقاومة', 'المقاومات المتوازية تجمع مباشرة', 'القدرة محفوظة في البطارية فقط'], correctIndex: 0,
    explanation: 'قاعدة النقاط تعبر عن حفظ الشحنة: مجموع التيارات الداخلة يساوي الخارجة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  // ========================= العلوم الحياتية =========================
  ExamQuestion(
    id: 'v6-bio-u1-01', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'المركبات العضوية الحيوية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'الوحدات البنائية الأساسية للبروتينات هي:',
    options: ['الأحماض الأمينية', 'الأحماض الدهنية', 'السكريات الثنائية', 'النيوكليوتيدات فقط'], correctIndex: 0,
    explanation: 'تتكون البروتينات من سلاسل من الأحماض الأمينية.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u1-02', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'الإنزيمات وجزيء حفظ الطاقة ATP', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'الدور الرئيس للإنزيم في التفاعل الكيميائي الحيوي هو:',
    options: ['خفض طاقة التنشيط', 'رفع درجة حرارة الخلية دائمًا', 'استهلاك جميع النواتج', 'تغيير ناتج الاتزان النهائي بالضرورة'], correctIndex: 0,
    explanation: 'الإنزيمات محفزات حيوية تخفض طاقة التنشيط وتزيد سرعة التفاعل.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u1-03', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'الإنزيمات وجزيء حفظ الطاقة ATP', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'يُعد ATP في الخلية بصورة أساسية:',
    options: ['جزيئًا لنقل الطاقة واستعمالها', 'حمضًا دهنيًا بنيويًا', 'هرمونًا ستيرويديًا', 'صبغة ضوئية'], correctIndex: 0,
    explanation: 'ATP وسيط رئيس لتخزين الطاقة ونقلها في العمليات الخلوية.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u1-04', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'المركبات العضوية الحيوية', difficulty: 'متوسط', skill: 'ربط',
    text: 'أي المركبات الآتية يدخل بصورة رئيسة في بناء الغشاء البلازمي؟',
    options: ['الليبيدات المفسفرة', 'النشا فقط', 'الغلايكوجين فقط', 'DNA فقط'], correctIndex: 0,
    explanation: 'الطبقة الثنائية للغشاء البلازمي تعتمد أساسًا على الليبيدات المفسفرة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u1-05', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'المركبات العضوية الحيوية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'الوحدة البنائية للحموض النووية هي:',
    options: ['النيوكليوتيد', 'الحمض الأميني', 'الغليسرول', 'الغلوكوز فقط'], correctIndex: 0,
    explanation: 'DNA وRNA بوليمرات مكونة من نيوكليوتيدات.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-bio-u2-01', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'دورة الخلية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'يتضاعف DNA في دورة الخلية خلال طور:',
    options: ['G1', 'S', 'G2', 'M فقط'], correctIndex: 1,
    explanation: 'طور S من المرحلة البينية هو طور تضاعف DNA.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u2-02', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'دورة الخلية', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'الوظيفة الأساسية لنقاط المراقبة في دورة الخلية هي:',
    options: ['التحقق من جاهزية الخلية وسلامة خطوات الدورة قبل التقدم', 'إنتاج ATP فقط', 'تحويل DNA إلى بروتين مباشرة', 'منع جميع الخلايا من الانقسام'], correctIndex: 0,
    explanation: 'نقاط المراقبة توقف أو تسمح بتقدم الدورة وفق سلامة الظروف والـDNA وارتباط الكروموسومات.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u2-03', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'الانقسام الخلوي وأهميته', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'الانقسام المتساوي يؤدي عادةً إلى تكوين:',
    options: ['نواتين متماثلتين وراثيًا من نواة أصلية', 'أربع خلايا أحادية المجموعة دائمًا', 'جزيء ATP', 'أمشاج فقط'], correctIndex: 0,
    explanation: 'الانقسام المتساوي يوزع الكروموسومات المنسوخة لإنتاج نواتين متماثلتين وراثيًا غالبًا.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u2-04', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'تضاعف DNA والتعبير الجيني', difficulty: 'متوسط', skill: 'وظائف إنزيمات',
    text: 'أي إنزيم يعمل على فصل سلسلتي DNA في بداية عملية التضاعف؟',
    options: ['الهيليكيز', 'الليباز', 'الأميليز', 'البيبسين'], correctIndex: 0,
    explanation: 'الهيليكيز يفك الروابط ويفصل سلسلتي DNA لبدء التضاعف.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u2-05', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'تضاعف DNA والتعبير الجيني', difficulty: 'متوسط', skill: 'تسلسل عمليات',
    text: 'تحدث عملية الترجمة لتصنيع عديد الببتيد على:',
    options: ['الرايبوسومات', 'الجسيم المركزي فقط', 'الغشاء النووي فقط', 'الليسوسومات'], correctIndex: 0,
    explanation: 'الرايبوسوم يقرأ كودونات mRNA وتتم عليه عملية الترجمة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-bio-u3-01', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'وراثة الصفات المندلية', difficulty: 'سهل', skill: 'مصطلحات',
    text: 'أي تركيب جيني يُعد متغاير اللاقحة؟',
    options: ['AA', 'aa', 'Aa', 'A فقط'], correctIndex: 2,
    explanation: 'متغاير اللاقحة يحمل أليلين مختلفين للصفة مثل Aa.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u3-02', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'وراثة الصفات المندلية', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'في سيادة تامة لصفة يتحكم بها أليلان A وa، يظهر النمط المتنحي فقط عند التركيب:',
    options: ['AA', 'Aa', 'aa', 'AA أو Aa'], correctIndex: 2,
    explanation: 'في السيادة التامة يحتاج النمط المتنحي إلى نسختين من الأليل المتنحي.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u3-03', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'الوراثة بعد مندل', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'عندما يظهر في الفرد متغاير اللاقحة نمط ظاهري وسيط بين الأبوين، تسمى الحالة:',
    options: ['السيادة غير التامة', 'السيادة التامة', 'الطفرة الصامتة دائمًا', 'الارتباط الجنسي فقط'], correctIndex: 0,
    explanation: 'في السيادة غير التامة يكون النمط الظاهري للمتغاير وسيطًا بين النمطين.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u3-04', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'الطفرات والاختلالات الوراثية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'الطفرة الجينية هي بصورة عامة:',
    options: ['تغير في تسلسل DNA', 'انقسام سيتوبلازم طبيعي', 'إنتاج ATP', 'تضاعف عضيّات فقط'], correctIndex: 0,
    explanation: 'الطفرة تغير في المادة الوراثية وقد يكون على مستوى تسلسل DNA.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u3-05', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'وراثة الصفات المندلية', difficulty: 'متوسط', skill: 'تمييز',
    text: 'أي عبارة تميز النمط الجيني عن النمط الظاهري؟',
    options: ['النمط الجيني يصف تركيب الأليلات، والظاهري يصف الصفة الملاحظة', 'كلاهما يعني البيئة فقط', 'النمط الظاهري هو تسلسل DNA دائمًا', 'لا فرق بينهما'], correctIndex: 0,
    explanation: 'النمط الجيني هو التكوين الأليلي، أما الظاهري فهو التعبير أو الصفة الملحوظة الناتجة عنه مع أثر البيئة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),

  ExamQuestion(
    id: 'v6-bio-u4-01', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'أدوات التكنولوجيا الحيوية', difficulty: 'متوسط', skill: 'وظائف أدوات',
    text: 'تستخدم إنزيمات القطع في التكنولوجيا الحيوية أساسًا من أجل:',
    options: ['قطع DNA عند تسلسلات محددة', 'ترجمة mRNA إلى بروتين', 'إنتاج ATP مباشرة', 'إيقاف جميع الطفرات'], correctIndex: 0,
    explanation: 'إنزيمات القطع تتعرف مواقع محددة في DNA وتقطعها.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u4-02', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'أدوات التكنولوجيا الحيوية', difficulty: 'سهل', skill: 'تقنيات',
    text: 'الغرض الرئيس من تقنية PCR هو:',
    options: ['تضخيم مقطع محدد من DNA', 'فصل البروتينات فقط', 'إنتاج دهون ثلاثية', 'إيقاف النسخ'], correctIndex: 0,
    explanation: 'PCR تسمح بإنتاج أعداد كبيرة من نسخ مقطع DNA محدد.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u4-03', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'أدوات التكنولوجيا الحيوية', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'يُستخدم البلازميد في كثير من تطبيقات الهندسة الوراثية بوصفه:',
    options: ['ناقلًا وراثيًا', 'إنزيم هضم', 'سكرًا أحاديًا', 'هرمونًا'], correctIndex: 0,
    explanation: 'يمكن إدخال DNA مرغوب في البلازميد ثم نقله إلى خلية مضيفة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u4-04', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'أدوات التكنولوجيا الحيوية', difficulty: 'متوسط', skill: 'تحليل',
    text: 'في الرحلان الكهربائي الهلامي لقطع DNA، تتحرك القطع الأصغر عادةً:',
    options: ['مسافة أكبر خلال الهلام', 'مسافة أقل دائمًا', 'لا تتحرك', 'باتجاه عشوائي'], correctIndex: 0,
    explanation: 'تواجه القطع الأصغر مقاومة أقل داخل الهلام فتتحرك مسافة أكبر في الظروف نفسها.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v6-bio-u4-05', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'تطبيقات التكنولوجيا الحيوية', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'يشير DNA معاد التركيب إلى DNA:',
    options: ['جُمعت فيه مادة وراثية من مصدرين أو أكثر', 'لا يحتوي أي جينات', 'يوجد في الفيروسات فقط', 'يتكون من RNA حصراً'], correctIndex: 0,
    explanation: 'DNA معاد التركيب ينتج من دمج قطع DNA من مصادر مختلفة ضمن جزيء واحد.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
];

const allCurriculumUnits = <CurriculumUnit>[
  ...curriculumUnits,
  ...v6CurriculumUnits,
];

const allCurriculumQuestions = <ExamQuestion>[
  ...officialCurriculumQuestions,
  ...v6CurriculumQuestions,
  ...v7CurriculumQuestions,
];

int get allVerifiedCurriculumQuestionCount =>
    allCurriculumQuestions.where((q) => q.verifiedFromOfficialCurriculum).length;

List<CurriculumUnit> allUnitsForSubject(String subject) =>
    allCurriculumUnits.where((unit) => unit.subject == subject).toList(growable: false);
