import 'models.dart';
import 'curriculum_data.dart';

/// V7: أسئلة تدريبية أصلية إضافية مرتبطة ببنية المنهاج 2026-2027.
/// ليست أسئلة وزارية رسمية ولا نسخًا حرفية من الكتب.
const v7CurriculumQuestions = <ExamQuestion>[
  ExamQuestion(
    id: 'v7-en-01', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Continuous and perfect tenses', difficulty: 'سهل', skill: 'قواعد',
    text: 'Choose the correct sentence.',
    options: ['I have known her for five years.', 'I am knowing her for five years.', 'I know her since five years.', 'I have been know her for five years.'], correctIndex: 0,
    explanation: 'Stative know is normally used in the present perfect for a state continuing to the present.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-02', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Personality vocabulary', difficulty: 'متوسط', skill: 'مفردات',
    text: 'A person who is willing to consider new ideas is best described as:',
    options: ['open-minded', 'short-tempered', 'absent-minded', 'self-conscious'], correctIndex: 0,
    explanation: 'Open-minded means receptive to new ideas and viewpoints.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-03', subject: 'اللغة الإنجليزية', unit: 'Identity',
    lesson: 'Reading: language and the world', difficulty: 'صعب', skill: 'فهم',
    text: 'If a writer says a theory "oversimplifies" the relation between language and thought, the writer most likely means the theory:',
    options: ['makes the relationship seem less complex than it is', 'proves the relationship completely', 'rejects all evidence', 'focuses only on pronunciation'], correctIndex: 0,
    explanation: 'Oversimplify means present something as simpler than its real complexity.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-04', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Inversion and cleft sentences', difficulty: 'متقدم', skill: 'قواعد',
    text: 'Choose the grammatically correct inversion.',
    options: ['Never have I seen such a crowded station.', 'Never I have seen such a crowded station.', 'Never did I seen such a crowded station.', 'Never have seen I such a crowded station.'], correctIndex: 0,
    explanation: 'After negative adverbials such as Never, auxiliary-subject inversion is required.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-05', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Considering and comparing alternatives', difficulty: 'متوسط', skill: 'وظائف لغوية',
    text: 'Which sentence most clearly compares two alternatives?',
    options: ['Whereas the train is cheaper, the plane is much faster.', 'The train arrived yesterday.', 'Please show me your ticket.', 'The platform is crowded.'], correctIndex: 0,
    explanation: 'Whereas explicitly contrasts two alternatives.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-06', subject: 'اللغة الإنجليزية', unit: 'On the move',
    lesson: 'Writing: an email of complaint', difficulty: 'صعب', skill: 'كتابة',
    text: 'Which opening is most appropriate for a formal complaint email?',
    options: ['I am writing to complain about the delay to my journey.', 'Hey! Your service was awful!', 'What is wrong with you people?', 'I wanna tell you something bad.'], correctIndex: 0,
    explanation: 'A formal complaint should state the purpose clearly and use an appropriate register.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-07', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'The Passive', difficulty: 'متوسط', skill: 'قواعد',
    text: 'Choose the correct passive form: "They will announce the results tomorrow."',
    options: ['The results will be announced tomorrow.', 'The results will announce tomorrow.', 'The results are announcing tomorrow.', 'The results have announced tomorrow.'], correctIndex: 0,
    explanation: 'Future passive uses will be + past participle.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-08', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'Business vocabulary', difficulty: 'سهل', skill: 'مفردات',
    text: 'A company’s total money received from sales before costs are deducted is called:',
    options: ['revenue', 'refund', 'debt relief', 'discount'], correctIndex: 0,
    explanation: 'Revenue is income received from normal business activities, especially sales.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-09', subject: 'اللغة الإنجليزية', unit: 'Hard sell',
    lesson: 'Writing: a for-and-against essay', difficulty: 'متقدم', skill: 'كتابة',
    text: 'Which sentence best introduces a balanced counterargument?',
    options: ['On the other hand, critics argue that the policy may harm small businesses.', 'This idea is obviously perfect.', 'Everyone knows the other side is wrong.', 'There is no reason to discuss disadvantages.'], correctIndex: 0,
    explanation: 'A balanced essay signals and fairly presents an opposing view.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-10', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Advanced conditional structures', difficulty: 'متقدم', skill: 'قواعد',
    text: 'Choose the correct inverted conditional.',
    options: ['Had I known about the allergy, I would have chosen another dish.', 'Had I knew about the allergy, I would choose another dish.', 'Did I know about the allergy, I would have chosen another dish.', 'Have I known about the allergy, I chose another dish.'], correctIndex: 0,
    explanation: 'Third conditional inversion uses Had + subject + past participle.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-11', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Food adjectives and partitives', difficulty: 'سهل', skill: 'مفردات',
    text: 'Which expression is a correct partitive?',
    options: ['a slice of bread', 'a bread of slice', 'a piece breads', 'a loaf of water'], correctIndex: 0,
    explanation: 'A slice of bread is a standard partitive construction.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-12', subject: 'اللغة الإنجليزية', unit: 'Tastes',
    lesson: 'Writing: a restaurant review', difficulty: 'متوسط', skill: 'كتابة',
    text: 'Which feature is most suitable in a restaurant review?',
    options: ['A clear recommendation supported by specific details', 'Only a list of prices with no opinion', 'A formal scientific method section', 'No description of food or service'], correctIndex: 0,
    explanation: 'A review should evaluate the experience and support the recommendation with details.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-13', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Modal and related verbs', difficulty: 'صعب', skill: 'قواعد',
    text: 'Choose the best completion: "You ___ have told me earlier; I could have helped."',
    options: ['should', 'must to', 'can', 'would to'], correctIndex: 0,
    explanation: 'Should have + past participle expresses criticism or regret about a past action.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-14', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Dependent prepositions', difficulty: 'متوسط', skill: 'استخدام اللغة',
    text: 'Choose the correct phrase.',
    options: ['succeed in solving the problem', 'succeed at solve the problem', 'succeed on solving the problem', 'succeed to solving the problem'], correctIndex: 0,
    explanation: 'The standard pattern is succeed in + -ing form.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-en-15', subject: 'اللغة الإنجليزية', unit: 'Do your best',
    lesson: 'Study idioms and collocations', difficulty: 'صعب', skill: 'مفردات',
    text: 'If a student "goes the extra mile", the student:',
    options: ['makes more effort than is normally expected', 'stops studying completely', 'avoids all difficult tasks', 'copies another student’s work'], correctIndex: 0,
    explanation: 'Go the extra mile means make an additional effort beyond what is required.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-01', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'نظريتا الباقي والعوامل', difficulty: 'سهل', skill: 'تطبيق',
    text: 'إذا كان P(x)=x²-5x+6، فإن باقي قسمة P(x) على (x-2) يساوي:',
    options: ['0', '2', '-2', '6'], correctIndex: 0,
    explanation: 'بحسب نظرية الباقي نحسب P(2)=4-10+6=0.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-02', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'نظريتا الباقي والعوامل', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'إذا كان (x-3) عاملًا في P(x)، فأي عبارة صحيحة؟',
    options: ['P(3)=0', 'P(-3)=0', 'P(0)=3', 'P(3)=1'], correctIndex: 0,
    explanation: 'وفق نظرية العوامل يكون (x-a) عاملًا إذا وفقط إذا P(a)=0.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-03', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'الكسور الجزئية', difficulty: 'صعب', skill: 'تمثيل جبري',
    text: 'أي صورة تصلح لتحليل 1/[(x-1)(x+2)] إلى كسور جزئية؟',
    options: ['A/(x-1)+B/(x+2)', 'A/(x-1)² فقط', 'A/x+B/x²', 'A(x-1)+B(x+2)'], correctIndex: 0,
    explanation: 'عند وجود عاملين خطيين مختلفين تكون الصورة A/(x-1)+B/(x+2).',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-04', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'المتطابقات المثلثية', difficulty: 'سهل', skill: 'استدعاء',
    text: 'أي متطابقة صحيحة؟',
    options: ['sin²θ+cos²θ=1', 'sinθ+cosθ=1 دائمًا', 'tanθ=cosθ/sinθ', '1+tan²θ=sin²θ'], correctIndex: 0,
    explanation: 'المتطابقة الأساسية هي sin²θ+cos²θ=1.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-05', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'حل المعادلات المثلثية', difficulty: 'متوسط', skill: 'حل معادلات',
    text: 'إذا كان sin θ = 0 ضمن 0°≤θ≤360°، فإن الحلول هي:',
    options: ['0° و180° و360°', '90° فقط', '90° و270°', '45° و225°'], correctIndex: 0,
    explanation: 'جيب الزاوية يساوي صفرًا عند مضاعفات 180° ضمن المجال.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-06', subject: 'الرياضيات', unit: 'المتطابقات والمعادلات المثلثية',
    lesson: 'المتطابقات المثلثية', difficulty: 'متقدم', skill: 'تحويل',
    text: 'إذا كان cosθ ≠ 0 فإن tanθ·cosθ يساوي:',
    options: ['sinθ', 'cosθ', '1', 'secθ'], correctIndex: 0,
    explanation: 'tanθ=sinθ/cosθ، لذا حاصل الضرب يساوي sinθ.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-07', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'قواعد الاشتقاق', difficulty: 'سهل', skill: 'اشتقاق',
    text: 'مشتقة f(x)=3x²-4x+1 هي:',
    options: ['6x-4', '3x-4', '6x+1', 'x²-4'], correctIndex: 0,
    explanation: 'نشتق حدًا حدًا: 6x-4.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-08', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'قاعدة السلسلة', difficulty: 'متوسط', skill: 'اشتقاق',
    text: 'مشتقة (2x+1)³ تساوي:',
    options: ['6(2x+1)²', '3(2x+1)²', '6(2x+1)', '2(2x+1)³'], correctIndex: 0,
    explanation: 'باستخدام قاعدة السلسلة: 3(2x+1)²×2.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-09', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'تطبيقات المشتقة', difficulty: 'صعب', skill: 'استنتاج',
    text: 'إذا كانت f′(x)>0 على فترة، فإن f على تلك الفترة:',
    options: ['متزايدة', 'متناقصة', 'ثابتة حتمًا', 'غير معرفة'], correctIndex: 0,
    explanation: 'إشارة المشتقة الموجبة تدل على التزايد.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-10', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'تطبيقات المشتقة', difficulty: 'متقدم', skill: 'استنتاج',
    text: 'لدالة قابلة للاشتقاق، إذا تغيرت إشارة f′ من موجبة إلى سالبة عند x=c، فغالبًا توجد عند c:',
    options: ['قيمة عظمى محلية', 'قيمة صغرى محلية', 'نقطة انعطاف بالضرورة', 'لا شيء يمكن استنتاجه'], correctIndex: 0,
    explanation: 'الانتقال من التزايد إلى التناقص يدل على قيمة عظمى محلية.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-11', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'الأعداد المركبة', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'قيمة i² تساوي:',
    options: ['-1', '1', 'i', '-i'], correctIndex: 0,
    explanation: 'الوحدة التخيلية معرفة بحيث i²=-1.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-12', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'العمليات على الأعداد المركبة', difficulty: 'متوسط', skill: 'حسابات',
    text: '(3+2i)+(1-5i)=',
    options: ['4-3i', '4+7i', '2-3i', '3-5i'], correctIndex: 0,
    explanation: 'نجمع الأجزاء الحقيقية والتخيلية كلًا على حدة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-13', subject: 'الرياضيات', unit: 'الأعداد المركبة',
    lesson: 'العمليات على الأعداد المركبة', difficulty: 'صعب', skill: 'حسابات',
    text: '(2+i)(2-i)=',
    options: ['5', '3', '4+i', '4-i'], correctIndex: 0,
    explanation: 'هو حاصل ضرب مرافقين: 2²+1²=5.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-14', subject: 'الرياضيات', unit: 'التفاضل وتطبيقاته',
    lesson: 'الاشتقاق الضمني', difficulty: 'متقدم', skill: 'اشتقاق ضمني',
    text: 'إذا كان x²+y²=25، فإن dy/dx يساوي:',
    options: ['-x/y', 'x/y', '-y/x', '2x+2y'], correctIndex: 0,
    explanation: 'بالتفاضل الضمني: 2x+2y y′=0، إذن y′=-x/y.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-math-15', subject: 'الرياضيات', unit: 'الاقترانات والمقادير الجبرية',
    lesson: 'الكسور الجزئية', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'قبل تحليل كسر جبري إلى كسور جزئية، إذا كانت درجة البسط أكبر من أو تساوي درجة المقام فيلزم أولًا:',
    options: ['إجراء القسمة المطولة', 'اشتقاق البسط', 'تربيع المقام', 'حذف الحد الأعلى'], correctIndex: 0,
    explanation: 'يجب تحويل الكسر غير الحقيقي إلى كثير حدود مضافًا إلى كسر حقيقي بالقسمة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-01', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة الغازية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'عند ثبات كمية الغاز ودرجة حرارته، العلاقة بين الضغط والحجم هي:',
    options: ['عكسية', 'طردية', 'لا علاقة', 'تربيعية دائمًا'], correctIndex: 0,
    explanation: 'قانون بويل يقرر أن P يتناسب عكسيًا مع V عند ثبات T.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-02', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة الغازية', difficulty: 'متوسط', skill: 'حسابات',
    text: 'غاز حجمه 2 L عند ضغط 1 atm. إذا أصبح الضغط 2 atm عند ثبات الحرارة، فالحجم الجديد:',
    options: ['1 L', '2 L', '4 L', '0.5 L'], correctIndex: 0,
    explanation: 'P1V1=P2V2، لذا V2=(1×2)/2=1 L.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-03', subject: 'الكيمياء', unit: 'حالات المادة',
    lesson: 'الحالة السائلة', difficulty: 'صعب', skill: 'استنتاج',
    text: 'زيادة قوة التجاذب بين جزيئات سائل تؤدي غالبًا إلى:',
    options: ['ارتفاع درجة غليانه', 'انخفاض لزوجته دائمًا', 'زيادة ضغطه البخاري', 'اختفاء التوتر السطحي'], correctIndex: 0,
    explanation: 'القوى الأقوى تحتاج طاقة أكبر لفصل الجزيئات، فترتفع درجة الغليان.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-04', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'تصنيف المحاليل', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'المحلول المشبع عند درجة حرارة معينة هو محلول:',
    options: ['يحتوي أكبر كمية مذاب يمكن أن تذوب في تلك الظروف', 'لا يحتوي مذابًا', 'يحتوي مذيبًا فقط', 'تركيزه صفر'], correctIndex: 0,
    explanation: 'المشبع يحوي الحد الأقصى الذائب عند الظروف المحددة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-05', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'خصائص المحاليل', difficulty: 'متوسط', skill: 'حسابات',
    text: 'المولارية تساوي:',
    options: ['مولات المذاب/لتر المحلول', 'مولات المذاب/كغ المذيب', 'كتلة المذيب/حجم المذاب', 'حجم المذاب/مولات المذيب'], correctIndex: 0,
    explanation: 'تعريف المولارية M هو مولات المذاب لكل لتر من المحلول.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-06', subject: 'الكيمياء', unit: 'المحاليل',
    lesson: 'خصائص المحاليل', difficulty: 'متقدم', skill: 'استنتاج',
    text: 'إذابة مذاب غير متطاير في مذيب نقي تؤدي عادةً إلى:',
    options: ['خفض الضغط البخاري للمذيب', 'رفع الضغط البخاري دائمًا', 'عدم تغير درجة الغليان', 'خفض عدد جسيمات المحلول'], correctIndex: 0,
    explanation: 'وفق خواص التجمع، المذاب غير المتطاير يخفض الضغط البخاري للمذيب.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-07', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'عند الاتزان الديناميكي:',
    options: ['تتساوى سرعـتا التفاعل الأمامي والعكسي', 'تتساوى تراكيز جميع المواد بالضرورة', 'يتوقف التفاعلان', 'تنعدم النواتج'], correctIndex: 0,
    explanation: 'الاتزان ديناميكي لأن التفاعلين يستمران بالمعدل نفسه.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-08', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'إضافة عامل حفاز إلى نظام عند الاتزان تؤدي إلى:',
    options: ['الوصول إلى الاتزان أسرع دون تغيير موضعه', 'زيادة Kc', 'إزاحة الاتزان نحو النواتج دائمًا', 'إيقاف التفاعل العكسي'], correctIndex: 0,
    explanation: 'الحفاز يخفض طاقة التنشيط للمسارين ولا يغير K أو تركيب الاتزان.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-09', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'تعبيرات ثابت الاتزان والحسابات المتعلقة به', difficulty: 'صعب', skill: 'حسابات',
    text: 'للتفاعل A ⇌ 2B، تعبير Kc هو:',
    options: ['[B]²/[A]', '[A]/[B]²', '2[B]/[A]', '[B]/2[A]'], correctIndex: 0,
    explanation: 'ترفع تراكيز المواد لأس معاملات المعادلة الموزونة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-10', subject: 'الكيمياء', unit: 'الاتزان الكيميائي',
    lesson: 'الاتزان الكيميائي والعوامل المؤثرة فيه', difficulty: 'متقدم', skill: 'استنتاج',
    text: 'في تفاعل غازي يقل فيه عدد مولات الغاز باتجاه النواتج، زيادة الضغط بإزالة جزء من الحجم تدفع الاتزان غالبًا نحو:',
    options: ['النواتج', 'المتفاعلات', 'لا يتأثر مطلقًا', 'الاتجاه الماص للحرارة فقط'], correctIndex: 0,
    explanation: 'يرجح النظام الجانب الأقل في عدد مولات الغاز لمقاومة زيادة الضغط.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-11', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الحموض والقواعد', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'وفق برونستد-لوري، الحمض هو:',
    options: ['مانح بروتون', 'مستقبل بروتون', 'مانح نيوترون', 'مستقبل إلكترون حصراً'], correctIndex: 0,
    explanation: 'حمض برونستد-لوري يمنح H+.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-12', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الرقم الهيدروجيني ومحاليل الحموض والقواعد القوية', difficulty: 'متوسط', skill: 'حسابات',
    text: 'إذا كان [H3O+]=10⁻⁵ M فإن pH يساوي:',
    options: ['5', '9', '10', '14'], correctIndex: 0,
    explanation: 'pH=-log(10^-5)=5.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-13', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'محاليل الحموض والقواعد الضعيفة', difficulty: 'صعب', skill: 'استنتاج',
    text: 'عند ثبات الظروف، الحمض ذو Ka الأكبر يكون عادةً:',
    options: ['أقوى', 'أضعف', 'أكثر قاعدية', 'متعادلًا دائمًا'], correctIndex: 0,
    explanation: 'Ka الأكبر يدل على تأين أكبر وقوة حمضية أعلى.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-14', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الأملاح والأيون المشترك', difficulty: 'متقدم', skill: 'استنتاج',
    text: 'إضافة أيون مشترك إلى محلول إلكتروليت ضعيف تؤدي غالبًا إلى:',
    options: ['تقليل تأينه', 'زيادة تأينه إلى 100%', 'عدم التأثير مطلقًا', 'تحويله إلى عنصر'], correctIndex: 0,
    explanation: 'الأيون المشترك يزيح اتزان التأين نحو الصورة غير المتأينة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-chem-15', subject: 'الكيمياء', unit: 'الحموض والقواعد وتطبيقاتها',
    lesson: 'الرقم الهيدروجيني ومحاليل الحموض والقواعد القوية', difficulty: 'متوسط', skill: 'حسابات',
    text: 'عند 25°C إذا كان pH=9 فإن pOH يساوي:',
    options: ['5', '9', '14', '23'], correctIndex: 0,
    explanation: 'عند 25°C: pH+pOH=14، لذا pOH=5.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-01', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'الزخم الخطي والدفع', difficulty: 'سهل', skill: 'حسابات',
    text: 'جسم كتلته 2 kg يتحرك بسرعة 3 m/s. زخمه الخطي يساوي:',
    options: ['6 kg·m/s', '1.5 kg·m/s', '5 kg·m/s', '9 kg·m/s'], correctIndex: 0,
    explanation: 'p=mv=2×3=6.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-02', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'الزخم الخطي والدفع', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'الدفع المؤثر في جسم يساوي التغير في:',
    options: ['الزخم الخطي', 'الطاقة الكامنة فقط', 'الكتلة', 'الموقع فقط'], correctIndex: 0,
    explanation: 'مبرهنة الدفع-الزخم: J=Δp.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-03', subject: 'الفيزياء', unit: 'الزخم الخطي والتصادمات',
    lesson: 'تطبيقات على حفظ الزخم الخطي', difficulty: 'متقدم', skill: 'استنتاج',
    text: 'في نظام معزول أثناء تصادم، الكمية المحفوظة دائمًا هي:',
    options: ['الزخم الخطي الكلي', 'الطاقة الحركية لكل نوع من التصادم', 'سرعة كل جسم', 'تسارع كل جسم'], correctIndex: 0,
    explanation: 'الزخم الخطي الكلي محفوظ في النظام المعزول، بينما الطاقة الحركية لا تحفظ في التصادم غير المرن.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-04', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'العزم والاتزان السكوني', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'يزداد مقدار العزم لقوة معينة عندما:',
    options: ['تزداد المسافة العمودية عن محور الدوران', 'تقل القوة إلى صفر', 'تصبح القوة موازية لذراع العزم تمامًا', 'تطبق القوة عند المحور'], correctIndex: 0,
    explanation: 'τ=rF sinθ، فيزداد مع ذراع العزم العمودي.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-05', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'ديناميكا الحركة الدورانية', difficulty: 'متوسط', skill: 'حسابات',
    text: 'إذا كان عزم محصل مقداره 8 N·m يؤثر في جسم عزمه القصوري 2 kg·m²، فإن تسارعه الزاوي:',
    options: ['4 rad/s²', '16 rad/s²', '6 rad/s²', '0.25 rad/s²'], correctIndex: 0,
    explanation: 'τ=Iα، إذن α=8/2=4.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-06', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'الزخم الزاوي', difficulty: 'صعب', skill: 'استنتاج',
    text: 'متزلج يدور ثم يضم ذراعيه إلى جسمه دون عزم خارجي ملحوظ. سرعته الزاوية:',
    options: ['تزداد', 'تقل إلى صفر', 'لا تتغير مطلقًا', 'تعتمد على كتلته فقط'], correctIndex: 0,
    explanation: 'بحفظ الزخم الزاوي، نقص العزم القصوري يؤدي إلى زيادة السرعة الزاوية.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-07', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'المجال الكهربائي', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'اتجاه المجال الكهربائي عند نقطة يعرف باتجاه القوة المؤثرة في:',
    options: ['شحنة اختبار موجبة', 'شحنة اختبار سالبة فقط', 'جسم متعادل فقط', 'مغناطيس شمالي'], correctIndex: 0,
    explanation: 'يُعرّف اتجاه المجال باتجاه القوة على شحنة اختبار موجبة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-08', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'المجال الكهربائي', difficulty: 'متوسط', skill: 'حسابات',
    text: 'إذا أثرت قوة 6 N في شحنة اختبار 2 C، فإن شدة المجال:',
    options: ['3 N/C', '12 N/C', '8 N/C', '0.33 N/C'], correctIndex: 0,
    explanation: 'E=F/q=6/2=3 N/C.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-09', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'الجهد الكهربائي', difficulty: 'متقدم', skill: 'مفاهيم',
    text: 'الجهد الكهربائي كمية:',
    options: ['قياسية', 'متجهة دائمًا', 'لا وحدة لها', 'تساوي المجال دائمًا'], correctIndex: 0,
    explanation: 'الجهد الكهربائي كمية قياسية وتقاس بالفولت.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-10', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'المقاومة والقوة الدافعة الكهربائية', difficulty: 'سهل', skill: 'حسابات',
    text: 'يمر تيار 2 A في مقاومة 5 Ω. فرق الجهد عبرها:',
    options: ['10 V', '2.5 V', '7 V', '0.4 V'], correctIndex: 0,
    explanation: 'V=IR=2×5=10 V.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-11', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'الدارة البسيطة والقدرة الكهربائية', difficulty: 'متوسط', skill: 'حسابات',
    text: 'جهاز يعمل عند 12 V ويسحب 3 A. قدرته الكهربائية:',
    options: ['36 W', '4 W', '15 W', '9 W'], correctIndex: 0,
    explanation: 'P=VI=12×3=36 W.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-12', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'توصيل المقاومات وقاعدتا كيرشوف', difficulty: 'صعب', skill: 'حسابات',
    text: 'مقاومتان 3 Ω و6 Ω موصولتان على التوازي. المقاومة المكافئة:',
    options: ['2 Ω', '9 Ω', '3 Ω', '18 Ω'], correctIndex: 0,
    explanation: '1/Req=1/3+1/6=1/2، إذن Req=2 Ω.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-13', subject: 'الفيزياء', unit: 'التيار الكهربائي',
    lesson: 'توصيل المقاومات وقاعدتا كيرشوف', difficulty: 'متقدم', skill: 'استنتاج',
    text: 'قاعدة كيرشوف للوصلات تعبّر أساسًا عن حفظ:',
    options: ['الشحنة الكهربائية', 'الطاقة الميكانيكية فقط', 'الزخم', 'الكتلة النووية'], correctIndex: 0,
    explanation: 'مجموع التيارات الداخلة إلى وصلة يساوي الخارجة منها نتيجة حفظ الشحنة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-14', subject: 'الفيزياء', unit: 'الكهرباء السكونية',
    lesson: 'الجهد الكهربائي', difficulty: 'صعب', skill: 'استنتاج',
    text: 'إذا تحركت شحنة موجبة تلقائيًا مع اتجاه المجال الكهربائي، فإن جهدها الكهربائي عادةً:',
    options: ['ينخفض', 'يرتفع دائمًا', 'يبقى ثابتًا دائمًا', 'يصبح سالبًا بالضرورة'], correctIndex: 0,
    explanation: 'اتجاه المجال هو اتجاه الانخفاض في الجهد الكهربائي.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-phy-15', subject: 'الفيزياء', unit: 'الحركة الدورانية',
    lesson: 'العزم والاتزان السكوني', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'شرط الاتزان الدوراني لجسم هو أن:',
    options: ['محصلة العزوم تساوي صفرًا', 'محصلة القوى فقط تساوي صفرًا ولو كان يدور بتسارع', 'العزم القصوري يساوي صفرًا', 'السرعة الزاوية تساوي صفرًا دائمًا'], correctIndex: 0,
    explanation: 'الاتزان الدوراني يتطلب Στ=0؛ وللاتزان السكوني الكامل يلزم أيضًا ΣF=0.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-01', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'المركبات العضوية الحيوية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'الوحدات البنائية للبروتينات هي:',
    options: ['الأحماض الأمينية', 'الأحماض الدهنية', 'النيوكليوتيدات', 'السكريات الثنائية'], correctIndex: 0,
    explanation: 'البروتينات بوليمرات مكونة من أحماض أمينية.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-02', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'الإنزيمات وجزيء حفظ الطاقة ATP', difficulty: 'متوسط', skill: 'مفاهيم',
    text: 'الوظيفة الرئيسة للإنزيم هي:',
    options: ['خفض طاقة التنشيط', 'زيادة ΔG للتفاعل', 'استهلاك نفسه بالكامل', 'تغيير نواتج التفاعل إلى مواد مختلفة دائمًا'], correctIndex: 0,
    explanation: 'الإنزيمات محفزات حيوية تخفض طاقة التنشيط دون أن تستهلك.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-03', subject: 'الأحياء', unit: 'كيمياء الحياة',
    lesson: 'الإنزيمات وجزيء حفظ الطاقة ATP', difficulty: 'صعب', skill: 'استنتاج',
    text: 'ارتفاع الحرارة كثيرًا فوق الدرجة المثلى للإنزيم قد يقلل نشاطه بسبب:',
    options: ['تغير بنيته الفراغية', 'زيادة عدد الروابط الببتيدية دائمًا', 'تحوله إلى DNA', 'تضاعف ATP تلقائيًا'], correctIndex: 0,
    explanation: 'الحرارة العالية قد تسبب تمسخ البروتين وتغير شكل الموقع الفعال.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-04', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'دورة الخلية', difficulty: 'سهل', skill: 'مفاهيم',
    text: 'يتضاعف DNA في دورة الخلية خلال طور:',
    options: ['S', 'G1', 'M فقط', 'السيتوكينيز'], correctIndex: 0,
    explanation: 'طور S من الطور البيني هو طور تضاعف DNA.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-05', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'الانقسام الخلوي وأهميته', difficulty: 'متوسط', skill: 'تمييز',
    text: 'الانقسام المتساوي ينتج عادةً:',
    options: ['خليتين متماثلتين وراثيًا تقريبًا', 'أربع خلايا أحادية دائمًا', 'جاميتات فقط', 'خلية واحدة مضاعفة'], correctIndex: 0,
    explanation: 'الانقسام المتساوي يحافظ على عدد الكروموسومات وينتج خليتين بنتين متشابهتين غالبًا.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-06', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'تضاعف DNA والتعبير الجيني', difficulty: 'متقدم', skill: 'تسلسل عمليات',
    text: 'أي ترتيب يمثل انتقال المعلومات الوراثية في التعبير الجيني بصورة عامة؟',
    options: ['DNA → RNA → Protein', 'Protein → DNA → RNA', 'RNA → Lipid → DNA', 'ATP → DNA → Glucose'], correctIndex: 0,
    explanation: 'المبدأ المركزي يصف النسخ من DNA إلى RNA ثم الترجمة إلى بروتين.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-07', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'وراثة الصفات المندلية', difficulty: 'سهل', skill: 'مصطلحات',
    text: 'الفرد الذي يحمل أليلين متماثلين لجين معين يسمى:',
    options: ['متماثل اللاقحة', 'متغاير اللاقحة', 'متعدد الجينات', 'هجين خلوي'], correctIndex: 0,
    explanation: 'Homozygous يعني وجود أليلين متماثلين.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-08', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'وراثة الصفات المندلية', difficulty: 'متوسط', skill: 'استنتاج',
    text: 'في تزاوج Aa × Aa، احتمال النمط الجيني aa يساوي:',
    options: ['1/4', '1/2', '3/4', '1'], correctIndex: 0,
    explanation: 'النسب الجينية هي 1 AA : 2 Aa : 1 aa.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-09', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'الوراثة بعد مندل', difficulty: 'صعب', skill: 'مفاهيم',
    text: 'في السيادة غير التامة، الفرد متغاير اللاقحة يظهر عادةً:',
    options: ['نمطًا ظاهريًا وسيطًا', 'صفة الأليل السائد كاملة دائمًا', 'صفة متنحية فقط', 'عدم وجود صفة'], correctIndex: 0,
    explanation: 'السيادة غير التامة تنتج نمطًا وسيطًا في المتغاير.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-10', subject: 'الأحياء', unit: 'الوراثة',
    lesson: 'الطفرات والاختلالات الوراثية', difficulty: 'متقدم', skill: 'استنتاج',
    text: 'طفرة استبدال قاعدة قد تكون صامتة إذا:',
    options: ['لم تغيّر الحمض الأميني المشفر', 'حذفت كروموسومًا كاملًا', 'أوقفت تضاعف DNA دائمًا', 'زادت عدد الخلايا'], correctIndex: 0,
    explanation: 'بسبب ترادف الشفرة الجينية قد يرمز الكودون الجديد للحمض الأميني نفسه.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-11', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'أدوات التكنولوجيا الحيوية', difficulty: 'سهل', skill: 'تقنيات',
    text: 'تقنية PCR تستخدم أساسًا لـ:',
    options: ['تضخيم DNA', 'ترجمة البروتين', 'فصل الدهون', 'قياس ضغط الدم'], correctIndex: 0,
    explanation: 'PCR تنتج نسخًا كثيرة من مقطع DNA محدد.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-12', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'أدوات التكنولوجيا الحيوية', difficulty: 'متوسط', skill: 'وظائف أدوات',
    text: 'وظيفة إنزيمات القطع هي:',
    options: ['قص DNA عند تسلسلات محددة', 'بناء ATP', 'تفكيك البروتينات في المعدة فقط', 'نسخ RNA إلى بروتين'], correctIndex: 0,
    explanation: 'Restriction enzymes تتعرف مواقع محددة في DNA وتقطعه.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-13', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'أدوات التكنولوجيا الحيوية', difficulty: 'صعب', skill: 'تحليل',
    text: 'في الرحلان الكهربائي الهلامي، تتحرك قطع DNA الأصغر عادةً:',
    options: ['مسافة أكبر', 'مسافة أقل دائمًا', 'لا تتحرك', 'في اتجاهين متعاكسين عشوائيًا'], correctIndex: 0,
    explanation: 'القطع الأصغر تعبر مسام الهلام بسهولة أكبر فتقطع مسافة أكبر.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-14', subject: 'الأحياء', unit: 'التكنولوجيا الحيوية',
    lesson: 'تطبيقات التكنولوجيا الحيوية', difficulty: 'متقدم', skill: 'مفاهيم',
    text: 'DNA معاد التركيب هو DNA:',
    options: ['يجمع مادة وراثية من مصادر مختلفة', 'يتكون من بروتين فقط', 'لا يحتوي جينات', 'يوجد طبيعيًا في خلية واحدة فقط بالضرورة'], correctIndex: 0,
    explanation: 'يُنشأ DNA معاد التركيب بدمج مقاطع وراثية من مصادر مختلفة.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
  ExamQuestion(
    id: 'v7-bio-15', subject: 'الأحياء', unit: 'دورة الخلية وتصنيع البروتينات',
    lesson: 'تضاعف DNA والتعبير الجيني', difficulty: 'متوسط', skill: 'وظائف إنزيمات',
    text: 'الإنزيم الذي يضيف نيوكليوتيدات جديدة أثناء تضاعف DNA هو:',
    options: ['DNA polymerase', 'Pepsin', 'ATP synthase فقط', 'Amylase'], correctIndex: 0,
    explanation: 'DNA polymerase يطيل السلسلة الجديدة بإضافة النيوكليوتيدات.',
    sourceLabel: officialSourceLabel, curriculumYear: currentCurriculumYear, verifiedFromOfficialCurriculum: true,
  ),
];